### ISSUE TITLE
Support more flexible logics

### ISSUE THREAD

**Issue by kaoet** [GoogleContainerTools/kpt#1018]
If I understand correctly, kpt has very limited functionalities in "computed variables". I didn't find the way to do the following things:
* `X = (Y == "true" ? Z + "-aabb": W + "-ccdd")`
* `X = base64(Y)`

And a step further, some resource-level logic, such as Deployment `D` should only exist if setter `S` is equal to "enabled".

**Comment by mortent** [comment]
So the goal of kpt is to support a config-as-data toolchain, so we don't plan to add features like embedding code into the manifests. Kpt provides some very limited support for very simple string interpolation with substitutions, but that is it.

The idea with kpt is that instead of trying to make your configuration very flexible by adding logic into the package, kpt provides a workflow for forking upstream packages and let you make any edits you want directly into your own copy. When there are upstream changes, you can use kpt to pull the upstream changes into your local package with merge logic that understand KRM resources and can do smart merging. For more complex scenarios you can use a kpt function to do transformations on your config. 

Do you have a more specific use-case where kpt doesn't work well?

**Comment by yuwenma** [comment]
+1 to what Morten said. close the issue
