### ISSUE TITLE
Remove 'kustomize build' function from the catalog

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1078]
It really doesn't make sense in any coherent e2e flow.

**Comment by frankfarzan** [comment]
Also need to remove the function code here:
https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/functions/ts/src

**Comment by aodinokov** [comment]
> Also need to remove the function code here:
> https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/functions/ts/src

Just thinking:
If this fn is deleted, and deeper integration between kpt and kustomize is implemented, how [export](https://googlecontainertools.github.io/kpt/reference/fn/export/) for such cases will work?
I guess the image will be required anyway by such workflow types as `cloud-build` for the cases when kpt calls kustomize, isn't it?
May be I'm wrong, since I don't have the full context of the planned changes... Don't get me wrong: I also think that calling kustomize_build from kpt, especially with fn-based plugins isn't the best solution  :)
