### ISSUE TITLE
Rationalize krmignore with the filtering resources in `pipeline run`

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1414]
We are filtering out resources during pipeline execution for ex. Kptfile, function configs etc. We need to investigate and support `krmignore` use-cases as well. Creating this for us to investigate first what needs to be done and then implement it.

**Comment by natasha41575** [comment]
Pipeline appears to already be ignoring files specified in .krmignore, because [the function localResources](https://github.com/GoogleContainerTools/kpt/blob/next/internal/pipeline/executor.go#L182) uses kyaml's [LocalPackageReader](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/kio/pkgio_reader.go#L175), which uses [ignoresFileMatcher](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/kio/pkgio_reader.go#L189) which [filters out files](https://github.com/mortent/kustomize/blob/master/kyaml/kio/ignorefilesmatcher.go) specified in .krmignore. 

I am making a PR for an e2e test that uses a .krmignore file to cover this case
