### ISSUE TITLE
kpt pkg get error message when package can't be retrieved is obscure

### ISSUE THREAD

**Issue by bgrant0607** [GoogleContainerTools/kpt#1527]
### Expected behavior

kpt pkg get of some non-existent package should say not found, doesn't exist, or somesuch.

### Actual behavior

```
error: failed to clone git repo: failed to clone git repo: trouble fetching submodules for master, please run 'git clone ; stat <DIR/SUBDIR>' to verify credentials: exit status 128
```

### Information

I failed to specify the branch of a repo. The default branch was not "main" or "master". Specifying the branch explicitly worked fine.

This was kpt 0.37.1.

**Comment by mortent** [comment]
This is addressed on the `next` branch, i.e. the implementation of the new kpt design.
First, we actually look at the `HEAD` symbolic reference to determine what is the default branch in the upstream repo, rather than guessing `main` or `master`. 
Second, if a ref is specified that doesn't exist, we print an error message that clearly explains the problem.
