### ISSUE TITLE
`kpt fn` error reporting and CLI output

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#1557]
`kpt fn render` should report errors with useful diagnostic info that helps the end-users as well as kpt developers. We should explore if we `kpt` can support error reporting explained in this [post](https://commandcenter.blogspot.com/2017/12/error-handling-in-upspin.html) by `Rob Pike`.  The approach in that post tries to strike the right balance with needs of both the personas.

In addition, being able to trace `input/output` for each function execution of the `pipeline` can assist in function level debugging as well.

**Comment by droot** [comment]
This is addressed with #1634

**Comment by frankfarzan** [comment]
Reopening this since we need to hash out the UX for error reporting and CLI output.

A list of all the data involved in running functions:

1. What function provides:
    1. ResourceList.results
    2. ResourceList.items
    3. stderr
    4. exit code
2. Orchestrator provides metadata:
    1. What function is running (Specially important when running a pipeline)

We need to figure out the best UX for providing all or subset of the following to the user across:

1. CLI output
    2. stdout
    3. stderr
4. FucntionResults files 

As part of this, need to consider happy paths and failure paths:

1. Happy path: The pipeline ran successfully
2. Failure paths:
    1. Function exceptional failures (e.g. function segfaulted)
    2. Validator failures which are WAI (kubeval found an issue)
    3. Orchestrator failed for some reason (e.g. IO failures or user input issues)

Some principles to follow:
- Don’t pollute the CLI output unnecessarily (Especially in the happy path)
- Provide realtime information about what’s happening, especially for long-running operations. The CLI should not appear stuck for long periods of time with no progress.
- Follow and add to the style guide: go/kpt-errors-style-guide

**Comment by frankfarzan** [comment]
#1783 should be addressed as part of this.

**Comment by frankfarzan** [comment]
As part this, need to add e2e test cases for both `render` and `eval`: go/kpt-test-cases

**Comment by mortent** [comment]
Related to this, the current output while a pipeline is running is a little confusing. It prints
```
package ".": running function "gcr.io/kpt-fn/kubeval:v0.1": 
```
with the caret blinking at the end of the line. It looks like we expect some kind of user input.

**Comment by frankfarzan** [comment]
Yes, I want to see a design doc iterating on the UI here. There are good prior art for CLI showing task progress.

**Comment by natasha41575** [comment]
Adding that we should address the concerns raised here:
https://github.com/GoogleContainerTools/kpt/pull/1839#pullrequestreview-650567778

**Comment by Shell32-Natsu** [comment]
The works remained for this task are:
1. Aggregate structured results
2. Create results file.
3. Hash output for the behavior with CLI stdin and stdout

These tasks are coved by umbrella issue #1390. Subtasks: #1920, #1915

**Comment by Shell32-Natsu** [comment]
Close this with #1783 . The only thing remained in m2 is #1915. Please create new issues for bugs or features.
