### ISSUE TITLE
`kpt pkg get` blocks for a long time

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1618]
kpt pkg get https://github.com/kubernetes/website/content/en/examples/application/cassandra cassandra
$ fetching package content/en/examples/application/cassandra from https://github.com/kubernetes/website to ...

### Expected behavior

Fetch the package

### Actual behavior

Hangs (or a takes very long time)

### Information

0.39 mac os

### Steps to reproduce the behavior

**Comment by frankfarzan** [comment]
Note that even though that repo is large, shallow clone terminates in 7s:
```
 time git clone --depth 1 https://github.com/kubernetes/website.git                                                                                                                                                                                                                                                                        <<<
Cloning into 'website'...
remote: Enumerating objects: 6974, done.
remote: Counting objects: 100% (6974/6974), done.
remote: Compressing objects: 100% (6059/6059), done.
remote: Total 6974 (delta 1191), reused 4021 (delta 468), pack-reused 0
Receiving objects: 100% (6974/6974), 161.19 MiB | 7.36 MiB/s, done.
Resolving deltas: 100% (1191/1191), done.
Updating files: 100% (6510/6510), done.
git clone --depth 1 https://github.com/kubernetes/website.git  7.37s user 3.94s system 40% cpu 27.600 total
```

**Comment by frankfarzan** [comment]
We should also consider showing progress similar to clone, it's not good UX to be blocking for more than a few seconds without providing feedback.

**Comment by mortent** [comment]
So it does actually complete, but it is very slow. There are several reasons for this:
 * kpt first tries to fetch it using the package-specific ref (which in this case is `content/en/examples/application/cassandra/master`). But in this case this tag doesn't exist, so the initial attempt fails.
 * Each attempt actually tries fetching the repo two ways, first by fetching just the specified ref, and if that doesn't work, fetch the full repo and the hard reset to the desired ref.
 * The second attempt to just use the `master` ref succeeds, but even then it takes some time since it is a large repo.
 * kpt also downloads git submodules.

So overall this adds up. We should look into whether there are ways to speed this up.

And yes to providing feedback on progress. This applies to several kpt commands.

**Comment by frankfarzan** [comment]
May want to split this into 2 issues: speeding up `get` and showing progress. For this package, it's really don't matter if it takes X minutes or it never terminates, the user won't stick around to find out.

**Comment by mortent** [comment]
The performance of the example here is improved substantially by the changes in https://github.com/GoogleContainerTools/kpt/pull/1778. There is still room to improve however, and we have a more specific issue to reduce the number of files we need to copy during get/update: https://github.com/GoogleContainerTools/kpt/issues/1807

The UX to show progress has also been improved, but this also remains something we'll continue to improve.

Based on this, I'm closing this issue.
