### ISSUE TITLE
Functions e2e test harness should test CLI output

### ISSUE THREAD

**Issue by frankfarzan** [GoogleContainerTools/kpt#1666]
We want to test expected error messages and non-structured results.

**Comment by frankfarzan** [comment]
One complication here is testing on different OS's if the output contains paths. One pragmatic option is to only test the output on select platforms.

**Comment by droot** [comment]
Yes, for m2 milestone, we should target select platforms (Linux and OSX).

**Comment by natasha41575** [comment]
#1762 checks the CLI output - but it does a substring match rather than an exact match (discussion was in [this comment thread](https://github.com/GoogleContainerTools/kpt/pull/1762#discussion_r614997518)). 

For example, for validate-resource-failure, the actual stdout is:
`package "/var/folders/l9/fkxgtdvn3435dzj2zj4gj9x000rk3j/T/kpt-pipeline-e2e-113726026/validate-resource-failure": running function "gcr.io/kpt-fn/starlark:unstable": FAILED`

but the test case here checks for a substring:

https://github.com/GoogleContainerTools/kpt/blob/a9589f16690bc84e4f26973f1aa413a96ac3a919/e2e/testdata/fn-render/validate-resource-failure/.expected/config.yaml#L17

For now we believe this is sufficient for our use case.

**Comment by natasha41575** [comment]
reopening because the previous PR was just for fn render; I will update it for fn eval as well.

**Comment by frankfarzan** [comment]
As part of this, please audit the error messages to ensure they're clear and actionable and conform to go/kpt-errors-style-guide. Many of the error message I'm seeing have poor UX.

**Comment by natasha41575** [comment]
Added a comment https://github.com/GoogleContainerTools/kpt/issues/1783#issuecomment-825199107 listing the error messages that can be improved
