### ISSUE TITLE
Question: should `eval` mutate the `fnConfig` resource in the same directory as input resources

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1892]
For example, in https://github.com/GoogleContainerTools/kpt/tree/87191859fdef443395741d85e134e5aa1cd0f877/package-examples/pipeline-validate
~~The gatekeeper constraintTemplates and constraints are considered as function config, but they are passed to the functions using `resourceList.items`. If we drop constraintTemplates and constraints from the output, it will cause the corresponding resource file to be deleted in in-place hydration use case.
We'd better keep fn config when it's in `resourceList.items`.~~

It turned out that the root cause is that the set-labels function drops the `constraintTemplate` and the `constraint` resources because they have the `local-config` annotation.
It also causes the enforce-gatekeeper function to become a noop, since there are no configuration for it.

**Comment by frankfarzan** [comment]
Not sure I parsed this. The Gatekeeper functions doesn't have any `functionConfig`. What's the problem?

**Comment by mengqiy** [comment]
@frankfarzan Updated the issue after debugging it a bit.

We should have a consistent behavior in functions about how to handle resources with a `local-config` annotation.
One thing we can do is to never mutate resources with a `local-config` annotation and always pass them as is to output.

**Comment by frankfarzan** [comment]
If you're talking about 1.0 design: Why does `fn` commands care about `local-config` annotation? This annotation is only relevant to `live` commands and denotes whether a resource should be applied or not. Also note that function configs will not require this annotation since we know through the reference in `configPath` field that the resource should not be applied.

**Comment by mengqiy** [comment]
I agree with what you said. But I feel there are some use cases that are not streamlined.

When a user has resources and fn config in the same directory, the experience of `kpt fn eval` is not streamlined.

Taking https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/starlark/simple as an example.
The starlark script set `.metadata.namespace` in all resources.

The **current** behavior:
We have the following files initially:
```sh
├── README.md
├── fn-config.yaml
└── resources.yaml
```

After we run `kpt fn eval --image=gcr.io/kpt-fn/starlark:v0.1 --fn-config=fn-config.yaml`, file `fn-config.yaml` will be removed, because the resource in `fn-config.yaml` is in the input `resourceList.items`, but is NOT in the output `resourceList.items`.
```sh
├── README.md
└── resources.yaml
```

Is the current behavior expected?

An **alternative** is to not filter the fn-config resource in the input `resourceList.items` and treat everything as normal resources. But it still has a minor issue.
After we run `kpt fn eval --image=gcr.io/kpt-fn/starlark:unstable --fn-config=fn-config.yaml`, we still have 3 files:
```sh
├── README.md
├── fn-config.yaml
└── resources.yaml
```

But you can see the `fn-config.yaml` has been modified.
```sh
$ git diff fn-config.yaml
diff --git a/examples/starlark/simple/fn-config.yaml b/examples/starlark/simple/fn-config.yaml
index cf1807a..1e31815 100644
--- a/examples/starlark/simple/fn-config.yaml
+++ b/examples/starlark/simple/fn-config.yaml
@@ -2,6 +2,7 @@ apiVersion: fn.kpt.dev/v1alpha1
 kind: StarlarkRun
 metadata:
   name: set-namespace-to-prod
+  namespace: prod
   annotations:
     config.k8s.io/function: |
       container:
```


@frankfarzan Any suggestion about a more streamlined UX?

**Comment by mengqiy** [comment]
cc: @droot @Shell32-Natsu

**Comment by frankfarzan** [comment]
OK, so you're describing a specific scenario where:
a) You're using `eval`
b) `fnConfig` happens to be in the same directory as resources you're operating on.

My first question is: are you sure you don't want to user `render` instead? In what scenario are you packaging the resources and `functionConfig` together but don't want to declare a pipeline?

For sake of discussion, assuming this is a real-world use case (and not synthesized for testing purposes). The question is specifically about the behavior of `eval`. This has nothing to do with `local-config` or `render`. Specifically: Should `eval` also mutate the `fnConfig` or leave it intact? Note that in 1.0 design, the only way you know such a resource is a `fnConfig` is the fact it's passed as a flag to `eval` (Otherwise there's no annotations).

**Comment by mengqiy** [comment]
> My first question is: are you sure you don't want to user render instead? In what scenario are you packaging the resources and functionConfig together but don't want to declare a pipeline?

I'm not sure. Most users probably will declare a pipeline. I'm just examining to ensure the behavior for running functions is not confusing to users.

We anyway need to fix set-annotations, set-labels and set-namespace to stop the behavior of removing resources with `local-config`. Otherwise, packages like https://github.com/GoogleContainerTools/kpt/tree/87191859fdef443395741d85e134e5aa1cd0f877/package-examples/pipeline-validate won't work.

**Comment by mengqiy** [comment]
If there are no AIs here we can close this.
