### ISSUE TITLE
fn render invariant: functions should not be able to modify resources outside of their current package

### ISSUE THREAD

**Issue by natasha41575** [GoogleContainerTools/kpt#1958]
When running `kpt fn render`, a function in a package should only be able to modify and generate resources within the current package. If it tries to write outside of its package, kpt should fail with error.

i.e. fn-render/path-index-ancestor and fn-render/path-index-outofpkg should fail with exit code 1. 

cc @frankfarzan @droot @Shell32-Natsu 

ref: https://github.com/GoogleContainerTools/kpt/issues/1559

**Comment by Shell32-Natsu** [comment]
Does this restriction apply to out-place render? @droot

**Comment by droot** [comment]
> Does this restriction apply to out-place render?

`out-of-place` render is orthogonal because functions themselves don't write to the filesystem, orchestrator does. `Functions` can recommend (or transform) the location of a resource by changing `path and index` annotations. So this issue is more about what transformations are allowed to `path and index` annotations by functions. Once we define that, orchestrator can enforce that. And Initially being restrictive is good idea and we can evolve the invariant as we learn more about use-cases.
