### ISSUE TITLE
Output from `kpt live preview` and `kpt live apply` can be confusing

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#1964]
The output from `kpt live preview` includes information about which operation would be performed, but it isn't obvious what the categories mean and the results from `preview` and `live` are different.

The categories and the output is aligned with kubectl, and there are good reasons for why the output will differ between `apply` and `preview`.

We should look into whether there are ways to improve the output here. One possibility is to optimize the UX more towards server-side apply, in which case I don't think the client will know specifically which operation was performed by the server.

**Comment by seans3** [comment]
* Specifically, client-side `preview` reports all resources that are `Unchanged` as `Configured`. Basically, client-side preview does not know if an resource will be changed or not. This is an artifact of `kubectl` client-side `dry-run`, and is not easily fixed. Moving to server-side `preview` will fix this problem.
* Objects which are changes are reported as `Configured`. Maybe a better term might be `Updated`.
* The other classes are self-explanatory, well understood by our customers who have `kubectl` experience, and I do not think they need to be changed: `Created`, `Unchanged`, `Failed`, and `Pruned`.
* There has been noticeable confusion about the difference between the `preview` command and the `diff` command. We might want to consider removing the `diff` command.
* Server-side `apply`, `preview`, and `diff` is higher fidelity because the calculations occur at the API Server which has more context than the client. Specifically, validation will be better because server-side validation is stronger and it includes validating and mutating web hooks. Switching to server-side versions of these commands will fix some problems. Since we will introduce significant changes in v1.0, maybe we should take the opportunity to move to the server-side versions of these commands by default. BUT...there are thorny issues around resources with `last-applied-annotation` from client-side apply that are subsequently server-side applied.

**Comment by mortent** [comment]
We have removed the preview and diff commands. So closing this issue.
