### ISSUE TITLE
Functions should complain about unknown keys in the ConfigMap

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#1988]
Functions should complain about unknown keys in the ConfigMap because it can be a potential typo by the user.

**Comment by mengqiy** [comment]
We should have this for both go and ts functions.

**Comment by mengqiy** [comment]
If we run the following: 
`kpt fn eval imperative --image=gcr.io/kpt-fn/kubeval:unstable -- schema_locationnn="somplace"`

It will succeed even though there is a typo in `schema_location`. Because it will use the default value for `schema_location` and ignore the unknown key-value pair in the ConfigMap.

**Comment by mengqiy** [comment]
Ideally this can be done in TS and golang SDK.

**Comment by runewake2** [comment]
Many go functions are directly invoking [kyaml](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/85b5b7de0b683c14f69b162cee1a64df47cc3c5d/functions/go/apply-setters/main.go#L47). We could introduce a wrapper around kyaml that adds an error for this but I don't think this would be a good error to add to kyaml itself.

I think we can introduce a new error/exception for this error in the sdk. [Typescript](https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/master/ts/kpt-functions/src/types.ts#L187)

```diff
  if (cm.data.hasOwnProperty(key)) {
    configMap.set(key, cm.data[key]);
+ } else {
+    throw new TypeError(`an unknown parameter (${key}) was provided to the function`)
+ }
```

That is raised when unknown parameters are provided. But since Go directly invokes kyaml I'm not sure how we want to approach that.

Introducing a new error type will be a breaking change for functions that rely on this and also will mean that functions can not ignore this behavior. It would cause this rule to be strictly enforced. This could cause issues if a function expects variably named keys. We may want to also have some strict/non-strict parsing (default to strict) that will cause errors or ignoring errors.

**Comment by mengqiy** [comment]
>   if (cm.data.hasOwnProperty(key)) {
>     configMap.set(key, cm.data[key]);
> + } else {
> +    throw new TypeError(`an unknown parameter (${key}) was provided to the function`)
> + }

This doesn't look right. Please take a look at [hasOwnProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) 
Function author needs to provide what are the known keys.

It may looks like in go:
```
func UnknownKey(key string, knownKeys StringSet) bool {
    // Return false if the key is not in the knownKeys.
}
for key := range cm {
    if !UnknownKey(key, knownKeys) {
        return fmt.Error("some error message")
    }
}
```

Similarly for TS.

**Comment by runewake2** [comment]
I've been referencing the kubeval function during this. `kubeval` is not mapping objects to a type but directly looking up objects by value https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/85b5b7de0b683c14f69b162cee1a64df47cc3c5d/functions/ts/kubeval/src/kubeval.ts#L30

That function explicitly ignores parameters that are not present right now: https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/85b5b7de0b683c14f69b162cee1a64df47cc3c5d/functions/ts/kubeval/src/kubeval.ts#L193

I can confirm on the Go side, but for Typescript this appears to be used as a `Map<string, TValue>`. Typescript's Map already returns undefined if the value is not found.

Is that enough (should we just update our existing functions to more strictly accept parameters) or would we like to map the ConfigMap data onto a type provided by the function and validate that? If we do not map to a type I'm not sure how we'd identify if a parameter was not provided or provided but misspelled. Both of those would result in a value not found in the map.

**Comment by runewake2** [comment]
I've put together a solution for Typescript that should provide this feature in a non-breaking, untyped way. I believe providing a typed option might be clearer, but I'm unsure how that approach would work between Typescript and Go, this version should allow both libraries to stay relatively in-line with one another.
