### ISSUE TITLE
upsert-resource function drops resource metadata annotation

### ISSUE THREAD

**Issue by martinmaly** [GoogleContainerTools/kpt#2188]
### Expected behavior

preserve annotations

### Information
Trying to customize [this](https://github.com/martinmaly/blueprints/blob/v.1.0-alpha2/hierarchy/simple/hierarchy.yaml#L7) with upsert-resource

`kpt version`
> 1.0.0-alpha.6

### Steps to reproduce the behavior

```
mkdir test
kpt pkg get https://github.com/martinmaly/blueprints.git/hierarchy/simple@v.1.0-alpha2 test/bp

cat <<EOF > test/args.yaml
{"apiVersion":"blueprints.cloud.google.com/v1alpha3","kind":"ResourceHierarchy","metadata":{"annotations":{"config.kubernetes.io/local-config":"true"},"name":"root-hierarchy","namespace":"hierarchy"},"spec":{"config":["Common","Development","Production","Testing"],"parentRef":{"external":"996501898304"}}}
EOF
```

`grep local test/bp/hierarchy.yaml`
>     config.kubernetes.io/local-config: 'true'

```
kpt1 fn eval test/bp \
    --image gcr.io/kpt-fn/upsert-resource:unstable \
    --results-dir test \
    --fn-config=test/args.yaml
```
note that the annotation `"annotations":{"config.kubernetes.io/local-config":"true"` disappeared.

**Comment by phanimarupaka** [comment]
@martinmaly This was intentional. 

It is difficult to know the intent of the user in this scenario. Adding `local-config` annotation to `args.yaml` in this case can be interpreted in 2 ways:
1. You want to treat `args.yaml` to be local.
2. You want to pass that annotation to `hierarchy.yaml` 

Remember, upsert resource function replaces entire resource with the input function config, so it shouldn't retain annotations of existing resource.

However, we have to choose a sensible default to `local-config` meta annotation(which will be deprecated eventually) which is to retain it if the existing resource already has it. Users should delete it manually if they don't want to retain it.

Does that sound good ? 

cc @frankfarzan

**Comment by martinmaly** [comment]
Thank you. I understand the distinction between the 2 cases but I am not sure I see the 1) as a valid use case, especially as the instruction to kpt is to "upsert this very resource into the config". In that case I'd expect that the resource is replaced fully, and the annotations from the function config are copied too. There may be use case I am missing though.

if local-config is being deprecated we can also switch the blueprint to the long-term supported mechanism. Is there a replacement that can be used now?

I cannot make a clear case for why upsert should either copy any metadata values from the original resource, especially if the same value is provided in the function config (this will mean we need to define some merge behavior). I am also not sure how deletion could be performed automatically (is there a 'delete part of config' kpt function that would be used)?

My main worry is simplicity of the upsert semantics. If we introduce conditional behaviors then the function will become harder to understand.

**Comment by phanimarupaka** [comment]
> There may be use case I am missing though.
What if you want to invoke this function declaratively using `kpt fn render`? In that case your `args.yaml` should reside within `bp` folder. And now read 1 and 2 points in my previous comment. I agree that this function is a perfect candidate for imperative invocation using `kpt fn eval` but we should support declarative invocation as well.

Regarding deprecating the annotation, it is still in design phase(go/ux-design-for-ignore). So can't suggest the alternative yet.

> "upsert this very resource into the config"
This is the ultimate goal without any doubt. But we should deal with these edge cases till we get there.

**Comment by martinmaly** [comment]
My understanding of kpt fn render is that the blueprint would look like follows:
* in Kptfile there would be preprocessor upsert-resource with function config that points at arts.yaml
* args.yaml (I believe) would not have meaning outside of the preprocessor pipeline; its purpose is still to be a function configuration for the preprocessor function - therefore, in my view, the concept of local config doesn't seem to apply

There probably still is some nuance I am missing.

**Comment by phanimarupaka** [comment]
1. `kpt live apply` doesn't accept duplicate resources in a directory.
2. If there are 2 same resources in a directory identified by GKNN, users can add local-config annotation to either of them.
3. In this example, the [fn-config](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/examples/upsert-resource/simple/fn-config.yaml) wants to replace the [Service](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/examples/upsert-resource/simple/resources.yaml#L2) resource. So after `kpt fn render` there will be duplicate resources in this package.
4. Current workaround is, if you add `local-config` annotation to [fn-config](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/examples/upsert-resource/simple/fn-config.yaml), the annotation is dropped by `upsert-resource` function, so that the upserted [Service](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/examples/upsert-resource/simple/resources.yaml#L2) resource can be applied while [fn-config](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/master/examples/upsert-resource/simple/fn-config.yaml) file can be ignored by `kpt live apply`
5. If we preserve `local-annotation`, then Service resource will not be applied by `kpt live apply`

Anyways, since we want to keep the semantics simple and achieve the goal of `upsert this very resource into the config`, I am fine with retaining the local-config annotation, meaning, `local-config` is just like any other annotation with no special handling. https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/358

**Comment by martinmaly** [comment]
Thank you, Phani!
