### ISSUE TITLE
Migration story for package consumers

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2221]
We need a clear and documented upgrade story for package consumers to move from kpt 0.39 to kpt 1.0. Consider the scenario:
1. I have checked out package version 1.0 with kpt 0.39.
2. The package author has published version 2.0, which is compatible with kpt 1.0.
3. As a package consumer, I would like to upgrade to kpt 1.0 (and package version 2.0).

Requirements:
1. Any local modifications are preserved, including setter values or direct edits.
2. I should not have to manually resolve “merge conflicts” if none of my local changes actually conflict with upstream changes.
3. I should not need to repeat the work of migrating to kpt 1.0 (since the upstream author has already done that).

**Comment by phanimarupaka** [comment]
> We need a clear and documented upgrade story for package consumers to move from kpt 0.39 to kpt 1.0. Consider the scenario:
> 
> 1. I have checked out package version 1.0 with kpt 0.39.
> 2. The package author has published version 2.0, which is compatible with kpt 1.0.
> 3. As a package consumer, I would like to upgrade to kpt 1.0 (and package version 2.0).
> 

Sure. I will create a separate section for package consumers upgrade steps in the migration doc. 

I don't think we can meet those requirements. Even consumers will have to do their part in the upgrade story. Here are the steps that consumer should follow(I will document them clearly)

1. Note the local changes they made to 1.0 version.
2. Fetch 2.0 package using `kpt1 pkg get`.
3. Perform the noted local changes on fetched package.

> Requirements:
> 
> 1. Any local modifications are preserved, including setter values or direct edits.

This is not possible because, in 3-way merge, we are talking about merging 0.39 version of package with 1.0 version of package. It is highly error-prone even if we attempt to do that. Consumers can declare the setter values and trigger `kpt fn render`

> 2. I should not have to manually resolve “merge conflicts” if none of my local changes actually conflict with upstream changes.

Again, this requires 3-way merge of different versions of packages, this is not possible. 

> 3. I should not need to repeat the work of migrating to kpt 1.0 (since the upstream author has already done that).

Consumers are not repeating the work here. They would just need to re-do their local changes and I think it will be mostly around setters.

**Comment by phanimarupaka** [comment]
cc @mikebz @mortent

**Comment by morgante** [comment]
> Perform the noted local changes on fetched package.

I don't think it's fair to ask users to re-make any local changes they have made.

> For comparison, other tools like Helm also needs package consumers to go through series of steps manual and automated to migrate from v2->v3, they do have a plugin similar to fix function but that is just a helper.

Helm doesn't ask users to redo their local customizations.

Asking consumers to run a series of migration commands is fine, but asking them to start over from scratch seems problematic.

**Comment by mikebz** [comment]
Looking at this scenario and given that we understand that kpt alpha1 -> v1 migration is not straightforward and can't be 100% automatic here is the question:

As a consumer if I just do the migration locally I will preserve my local changes (which could be even things like additional sub-packages), then what happens if I do an update from the new version?  If the changes I have are more or less in line with the changes that the upstream author had then I should be in a fairly good shape.  

The problem with a mix of manual and automatic migration is that the author could have migrated the package in a way that's not the same.

@morgante is this a request to help with your current private preview customers who will need to get migrated?  How many customers are we talking about?  Creating this algorithm might be harder than just helping them one by one.

**Comment by morgante** [comment]
> The problem with a mix of manual and automatic migration is that the author could have migrated the package in a way that's not the same.

This is my main concern. For example, I am having to *correct* the auto-migrated configuration for several of our LZ packages. I'm fine doing this, but it doesn't seem tenable to ask every LZ customer to also manually fix the migration in the same way I did.

**Comment by phanimarupaka** [comment]
To have a ball park, what are the 

> > The problem with a mix of manual and automatic migration is that the author could have migrated the package in a way that's not the same.
> 
> This is my main concern. For example, I am having to _correct_ the auto-migrated configuration for several of our LZ packages. I'm fine doing this, but it doesn't seem tenable to ask every LZ customer to also manually fix the migration in the same way I did.
> 
> > @morgante is this a request to help with your current private preview customers who will need to get migrated? How many customers are we talking about? Creating this algorithm might be harder than just helping them one by one.
> 
> We have ~100 customers in various states of usage. We don't need it to be 100% automatic, but some of them have customized the blueprints quite a bit. I'm concerned about asking them to repeat all their customizations.

To give a ballpark estimate, can we assume ~95% of users only modified setter values ? I am not sure if anyone did in-place edits and used `kpt pkg update` using 0.39 as the merge behavior is not documented anywhere and is broken. What are the other customizations we are talking about here ?

**Comment by morgante** [comment]
Some did more advanced customizations, but we could probably manually work with them on those. Setter-only modification should be seamless though.

**Comment by phanimarupaka** [comment]
Cool. Here is the PR for updated document. PTAL.

https://github.com/GoogleContainerTools/kpt/pull/2228

**Comment by morgante** [comment]
Thanks for adding the doc, I think just throwing away the existing package is insufficient though. At the very least I think we should capture previous setter values.

**Comment by phanimarupaka** [comment]
So are you suggesting we should have a new function which takes v0.39 package as input and outputs a ConfigMap resource with setters ? I am not sure if that solves the problem or introduces new problems. Why can't users can just invoke `kpt cfg list-setters` to know the current values of setters ? I don't think we will be saving much with that automation.

**Comment by phanimarupaka** [comment]
@morgante The docs are merged. Can you please confirm if it looks good and close this issue.

**Comment by morgante** [comment]
Thanks @phanimarupaka, the doc is helpful. I'm still concerned about asking users to manually replay operations, but we can await further customer input.

**Comment by phanimarupaka** [comment]
Sure. Please circle back with us if you hear different feedback from your customers. Closing this issue for now.
