### ISSUE TITLE
kpt v1 cannot render from a directory without a Kptfile

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#2285]
### Expected behavior
I should be able to run `kpt fn render` from a root directory with no Kptfile (but with child directories that potentially do have Kptfiles).

### Actual behavior
Kpt refuses to render, raising this error:
```
Error: No Kptfile found at "/Users/morgantep/code/google/anthos/blueprints-gh/catalog/hierarchy". 
```

### Information
This is a regression from kpt 0.3x.

**Comment by droot** [comment]
Thank you for reporting this. This is as per design, we need to document this better in our docs.

`fn render` is a bit different from the `fn run` command in `0.3x` when it comes to rendering the config.  `fn render` renders a **package hierarchy** in depth-first-order where resources from sub-package are render first, and then resources from subpackage rendering are re-rendered at the parent with parent package's pipeline. [Declarative Function Execution](https://kpt.dev/book/04-using-functions/01-declarative-function-execution) chapter covers the `fn render` in detail.

`render` detects package boundary by the presence of valid `Kptfile`, otherwise, it will not be able to differentiate between a directory without `kptfile` and directories with `kptfile`. Consider following examples of package hierarchy.

```
# Example 1
root-pkg
   Kptfile
   subdirA
     Kptfile
     r1
     r2

# Example 2
root-pkg
   Kptfile
   subdirA
     r1
     r2

```
In the example1, r1 and r2 belongs to subdirA subpackage, while in example2, r1 and r2 belongs to root-pkg. So having a strict notion of a package is important for `render` to determine the package hierarchy and apply functions.

If you are running functions imperatively, you will find `fn eval` behavior closer to `fn run` in 0.3x.

Is `catalog/hierarchy` a kpt package or not ? if it's a package, you should initialize Kptfile using `kpt pkg init` to run `kpt fn render` on it.

**Comment by morgante** [comment]
Are you saying we don't want to run `kpt fn render` in any sort of CI/CD workflow?

In the landing zone, we have a "source repo" which contains the unhydrated config of what we want to have deployed. It looks like this:

```
source-repo/
-- package-one/
---- Kptfile
---- resources.yaml
-- package-two/
---- Kptfile
---- subpackage/
------ Kptfile
```

In my Cloud Build set up, I want to render all packages in the repo (so Config Sync can then apply them to the cluster).

I am *not* asking to run imperative functions. This is simply asking to declaratively render all functions.

This is a major regression from kpt 0.3x and needs to be addressed before launch.

**Comment by frankfarzan** [comment]
In your example above, you are actually treating `source-repo` as a package that has two subpackages. To invoke render on the `source-repo` package, just create a minimal `Kptfile`. The following is a porcelain for this:

```shell
$ kpt pkg init source-repo
```

Definition of package:

`A package is explicitly declared using a file named Kptfile containing a KRM resource of kind Kptfile. The Kptfile contains metadata about the package and is just a regular resource in the YAML format.`

https://kpt.dev/book/02-concepts/01-packages

Render is one of the operations that can be done on the noun package, there are other operations that are defined on this noun and require `Kptfile` by definition:

https://kpt.dev/book/02-concepts/02-workflows

So this is not artificial constraint or specific to render, it's how a package is defined consistently across all functionality in kpt. And most other package managers have similar definition.

===================
Side note:

An alternative way to define a package would be to say each directory is a package (1-to-1 mapping), a package (i.e. a directory) may have zero or one Kptfile. This was briefly considered in early designs on but not chosen for several reasons.
===================

**Comment by morgante** [comment]
Hi @frankfarzan, thanks for weighing in. I agree with your assessment that `source-repo` is *implicitly* a package with two subpackages.

What I don't understand is why we need to force users to manually create a Kptfile just to run `kpt fn render`. If a content-less kpt package is sufficient to run `kpt render`, why do we force the toil of generating that package on users?

Respectfully, it *is* an artificial constraint if we force users to take a manual action which adds no new information to the system.

> Side note: An alternative way to define a package would be to say each directory is a package (1-to-1 mapping) and a package (i.e. a directory) may have zero or one Kptfile. This was briefly considered in early designs but not chosen for several reasons.

I was not aware we changed the definition from 0.39. Can you please share the design doc where it was approved to decide that all packages *must* have a Kptfile?

**Comment by frankfarzan** [comment]
Take @droot's example above, how would you know whether `root-pkg/subdirA` is a package? Should you be able to run  a command like `live apply` in that directory for Example 2?

In Example 2, running `render` or any other package operation (e.g. `live apply`) on that directory needs to produce a clear error message instead of silently trying to do the wrong thing. Accepting any directory as a package will lead to all sorts of foot-guts and inconsistencies like this. This is where providing consistent and simple definition of what a package is across all commands is more beneficial than small convenience of this implicit behavior for the render command. It's also much easier concept to explain to users.

The alternative model I described above was never implemented in kpt, only briefly considered. @mortent can provide more history here.

**Comment by morgante** [comment]
> Take @droot's example above, how would you know whether root-pkg/subdirA is a package? Should you be able to run a command like live apply in that directory for Example 2?

If a user decides to run from that directory, they should be able to do so.

> The alternative model I described above was never implemented in kpt, only briefly considered. @mortent can provide more history here.

In kpt 0.39, I could run `kpt pkg get` and `kpt fn run` without a Kptfile.

**Comment by frankfarzan** [comment]
So in your Cloud Build, you're doing this:

```shell
$ kpt pkg get <git-repo>/source-repo
$ kpt fn render source-repo
```

?

If so, note the following:

> There is one scenario where a Kptfile is implicit: You can use kpt to fetch any Git directory containing KRM resources, even if it does not contain a Kptfile. Effectively, you are telling kpt to treat that Git directory as a package. kpt automatically creates the Kptfile on the local filesystem to keep track of the upstream repo. This means that kpt is compatible with large corpus of existing Kubernetes configuration stored on Git today! For example, cockroachdb is just a vanilla directory of KRM: ```$ kpt pkg get https://github.com/kubernetes/examples/staging/cockroachdb```

https://kpt.dev/book/02-concepts/01-packages

On the local filesystem, the minimal Kptfile is automatically created. You can potentially take advantage of that feature, even though in your use case, you know you're dealing with kpt packages (and have declared sub-packages), so not sure what you're really gaining by avoiding making `source-repo` an explicit package.

**Comment by morgante** [comment]
Cloud Build already provides the Git repo, so I'm not running `kpt pkg get`.

Obviously I can work around this by inserting an auto-generated `kpt pkg init`, but it still seems suboptimal.

**Comment by mortent** [comment]
@morgante Some different options for what is considered a package and how to demarcate package boundaries were considered. In the end, we decided that defining a package by the presence of the Kptfile is the best option. Almost every kpt package requires the Kptfile to be useful (like the apply logic, update, diff..) and it allows us to create a UX that is consistently package-focused. The new kpt package design also avoids the different treatment of a root package vs a subpackage from previous versions of kpt, which extends to the requirement that packages must have a Kptfile.

How would you end up with a root package that doesn't have a Kptfile? If you are creating the package from scratch, it seems like you would want to start with creating the Kptfile. And if the package is cloned from a git repo, kpt will create the Kptfile automatically.

**Comment by droot** [comment]
> Obviously I can work around this by inserting an auto-generated `kpt pkg init`, but it still seems suboptimal.

Thinking from a package publisher's CUJ perspective, I am ready to create a new package which will contain other sub packages, doing the first step of `initializing the package` and declaring the intent explicitly with `kpt pkg init` seems very reasonable from UX perspective given that this needs to be done once in package's lifecycle.

**Comment by morgante** [comment]
> Thinking from a package publisher's CUJ perspective, I am ready to create a new package which will contain other sub packages, doing the first step of initializing the package and declaring the intent explicitly with kpt pkg init seems very reasonable from UX perspective given that this needs to be done once in package's lifecycle.

That's fine, I have no concerns with doing that for package publishers.

**Comment by droot** [comment]
We don't plan on supporting this, so closing this.
