### ISSUE TITLE
Support Kustomize

### ISSUE THREAD

**Issue by jrgirvan** [GoogleContainerTools/kpt#2388]
### Expected behavior

Running functions on packages with `kustomization.yaml` files works

### Actual behavior

```bash
❯ kpt fn eval --image gcr.io/kpt-fn/apply-setters:v0.1
[RUNNING] "gcr.io/kpt-fn/apply-setters:v0.1"
[FAIL] "gcr.io/kpt-fn/apply-setters:v0.1"
Error: input resource list must contain only KRM resources: kustomization.yaml: resource must have `metadata.name` 
```

### Information

```bash
❯ kpt version
1.0.0-beta.1
```
Adding `metadata.name` to the Kustomize file resolves the error, but `metadata` is not in the Kustomize spec 

### Steps to reproduce the behavior

Run `kpt fn eval --image gcr.io/kpt-fn/apply-setters:v0.1` a `kustomize.yaml` file

**Comment by mikebz** [comment]
@jrgirvan are you in control of the upstream package?  Can you add the metadata.name to it?

**Comment by jrgirvan** [comment]
Hi @mikebz 
Yes I am in control of it.
I did add the `metadata.name` to the `kustomization.yaml` file and is does resolve the issue.

When I created this issue, I thought `metadata` was not in the Kustomization type definition.
But on further inspection [here](https://github.com/kubernetes-sigs/kustomize/blob/7fae7d1bd63ef5f9ea0c2e11593581ed5974fbe9/api/types/kustomization.go#L27) it is
```go
MetaData *ObjectMeta `json:"metadata,omitempty" yaml:"metadata,omitempty"`
```
But it is optional
So given that it is optional, should it be enforced by kpt?

I'm happy is the answer is yes, I'll add it to my packages and and we can close this issue.

**Comment by mikebz** [comment]
@natasha41575 seems like this is something you added can you comment on IsKRM?

```
func IsKRM(n *yaml.RNode) error {
	meta, err := n.GetMeta()
	if err != nil {
		return fmt.Errorf("resource must have `apiVersion`, `kind`, and `name`")
	}
	if meta.APIVersion == "" {
		return fmt.Errorf("resource must have `apiVersion`")
	}
	if meta.Kind == "" {
		return fmt.Errorf("resource must have `kind`")
	}
	if meta.Name == "" {
		return fmt.Errorf("resource must have `metadata.name`")
	}
	return nil
}
```

**Comment by natasha41575** [comment]
This is something I've discussed with @droot on whether we should be enforcing `metadata.name` on kustomization files. 

We chose to require all resources (including kustomization files) to be valid KRM resources, which means they must have a `metadata.name` field. The idea is that if you run a resource through a function, you are going to hit this error anyway because functions are expected resources to be valid KRM resources. This way we can catch and throw the error early to help make functions simpler. Since a kustomization file can have a `metadata.name` field, there didn't seem to be a strong reason to make it an exception for now. 

@droot do you have anything to add?

**Comment by stefanhenseler** [comment]
@natasha41575 So, I think kustomization.yaml is not the only issue here. We use configmap generators in our bases, in case you have a JSON file, you run into the same issue. Kpt will complain about the Json file not being a valid KRM. Unfortunately, there is no way to fix this issue at the moment, adding metadata.name just doesn’t makes sense in this case. So what I would expect the kpt sdk to do, is to ignore all none KRM files and just not put them into the resource list. Because this would mean if you would miss anything in the resource list you got to add metadata.name and also make sure it’s a valid KRM

**Comment by droot** [comment]
@stefanhenseler kpt provides a mechanism to ignore non-KRM files using a file called `.krmignore`. It is not documented well at the moment, but we will be doing it soon. It works like `gitignore` where you can list the file patterns that you want kpt to ignore, so that will be right way to address the cases you described above.

@natasha41575 Thinking more about the user-journey here, users are primarily using kpt for package management, but using kustomize for rendering the config or preparing the resources (or the kustomization file itself) for rendering by running functions such as `apply-setters` imperatively. Given that it is causing so much friction on on-ramping kustomize users to kpt, it makes sense to relax this check (I know you proposed when first time this issue was discovered :)).

I have created a PR with tests to relax the check for KRM #2409 .

**Comment by droot** [comment]
The PR has been merged and will be available in beta.3 release next week.
