### ISSUE TITLE
Blank flag inputs in kyaml v0.10.7+

### ISSUE THREAD

**Issue by g-awmalik** [GoogleContainerTools/kpt#2521]
### Expected behavior
Flag inputs should be available as variables in the kpt functions when run/eval-ed as `-- value=foobar` where `value` is the flag name and `foobar` is the flag value

### Actual behavior
This seems to work fine up until kyaml v0.10.6. However for kyaml v.0.10.7+ the flag input values are evaluated as blanks or null when accessed in code using `cmd.Flags().StringVar(&value, "value", "", "annotation value")`

#### Valid flag value using kyaml v0.10.6:

```
package main

import (
	"os"

	"sigs.k8s.io/kustomize/kyaml/fn/framework"
	"sigs.k8s.io/kustomize/kyaml/yaml"
)

var value string

func main() {
	resourceList := &framework.ResourceList{}
	cmd := framework.Command(resourceList, func() error {
		// cmd.Execute() will parse the ResourceList.functionConfig into
		// cmd.Flags from the ResourceList.functionConfig.data field.
		for i := range resourceList.Items {
			// modify the resources using the kyaml/yaml library:
			if err := resourceList.Items[i].PipeE(yaml.SetAnnotation("myannotation", value)); err != nil {
				return err
			}
		}
		return nil
	})
	cmd.Flags().StringVar(&value, "value", "", "annotation value")
	if err := cmd.Execute(); err != nil {
		os.Exit(1)
	}
}
```

Build and run the function using `kpt fn eval --exec ./my-fn -- value=foobar`
This successfully annotates a resource file in the same directory with `myannotation: 'foobar'`

#### Invalid flag value using kyaml v0.10.7+:

```
// main.go
package main

import (
	"fmt"
	"os"

	"sigs.k8s.io/kustomize/kyaml/fn/framework"
	"sigs.k8s.io/kustomize/kyaml/fn/framework/command"
	"sigs.k8s.io/kustomize/kyaml/yaml"
)

func main() {
	var value string
	fn := func(rl *framework.ResourceList) error {
		for i := range rl.Items {
			// set the annotation on each resource item
			if err := rl.Items[i].PipeE(yaml.SetAnnotation("myannotation", value)); err != nil {
				return err
			}
		}
		return nil
	}
	cmd := command.Build(framework.ResourceListProcessorFunc(fn), command.StandaloneEnabled, false)
	cmd.Flags().StringVar(&value, "value", "", "annotation value")

	if err := cmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

Build and run the function using `kpt fn eval --exec ./my-fn -- value=foobar`
Running the function creates an annonation `myannotation` in resource however it is always set as blank no matter what the value is set as the command line argument.

**Comment by mengqiy** [comment]
@g-awmalik Thanks for catching this issue.
I had dug into this issue.
In kyaml v0.10.6, the `ResourceList` has a field called [`Flags`](https://github.com/kubernetes-sigs/kustomize/blob/kyaml/v0.10.6/kyaml/fn/framework/framework.go#L70-L83).  When `ResourceList.Read()` is invoked, these flags will be set according to `functionConfig.data`. See:  https://github.com/kubernetes-sigs/kustomize/blob/kyaml/v0.10.6/kyaml/fn/framework/framework.go#L207-L218
In kyaml v0.10.7+, when using `command.Build` we will not go through the code path in https://github.com/kubernetes-sigs/kustomize/blob/kyaml/v0.10.6/kyaml/fn/framework/framework.go#L207-L218. And the `Flags` field has been dropped in kyaml v0.10.13+.
`kyaml` is still in compliance with the [function spec](https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-spec.md), since the function spec never has a `flags` field.

We can do the following to make it work:
```go
func main() {
	// create a struct matching the structure of ResourceList.FunctionConfig to hold its data
	var config struct {
		Data map[string]string `yaml:"data"`
	}
	fn := func(items []*yaml.RNode) ([]*yaml.RNode, error) {
		for i := range items {
			// set the annotation on each resource item
			err := items[i].PipeE(yaml.SetAnnotation("value", config.Data["value"]))
			if err != nil {
				return nil, err
			}
		}
		return items, nil
	}
	p := framework.SimpleProcessor{Filter: kio.FilterFunc(fn), Config: &config}
	cmd := command.Build(p, command.StandaloneDisabled, false)

	if err := cmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
```

I will update the kpt document accordingly.

**Comment by mengqiy** [comment]
I created a PR https://github.com/GoogleContainerTools/kpt/pull/2525 to update the dev guide for golang

**Comment by mengqiy** [comment]
#2525 has been merged. We can close this issue.
