### ISSUE TITLE
kpt-functions-catalog e2e tests failing on gLinux

### ISSUE THREAD

**Issue by sdowell** [GoogleContainerTools/kpt#2606]
### Expected behavior
kpt-functions-catalog e2e tests pass on gLinux environment

### Actual behavior
kpt-functions-catalog e2e tests are not passing on gLinux. I am observing the following tests failing:

--- FAIL: TestE2E (0.25s)
    --- FAIL: TestE2E/../../tests/enable-gcp-services/nested-packages (23.07s)
    --- FAIL: TestE2E/../../examples/render-helm-chart-remote-values-file (6.24s)
    --- FAIL: TestE2E/../../examples/generate-folders-resourcehierarchy-v3 (7.40s)
    --- FAIL: TestE2E/../../examples/render-helm-chart-local (6.49s)
    --- FAIL: TestE2E/../../examples/kubeval-simple (8.60s)
    --- FAIL: TestE2E/../../examples/kubeval-imperative (7.24s)
    --- FAIL: TestE2E/../../examples/kubeval-mount-schema (8.25s)
    --- FAIL: TestE2E/../../examples/generate-folders-resourcehierarchy-v2 (9.47s)
    --- FAIL: TestE2E/../../examples/generate-folders-resourcehierarchy-v1 (8.85s)
    --- FAIL: TestE2E/../../examples/enable-gcp-services-advanced (7.02s)
    --- FAIL: TestE2E/../../examples/enable-gcp-services-simple (7.81s)
### Information

Kpt Version: 1.0.0-beta.9
GoogleContainerTools/kpt-functions-catalog at the tip of origin/master

### Steps to reproduce the behavior
```bash
cd path/to/kpt-functions-catalog
git fetch
git checkout origin/master
make build && make e2e-test
```

**Comment by rquitales** [comment]
I've managed to get the kpt-functions-catalog e2e fully passing on gLinux. Here are the following findings, and code that need to be patched to ensure all tests passes:

### Ensure dependencies satisfy required versions
  - kpt - must be pulled from `main`.
    `v1.0.0-beta.9` will cause the following test cases to fail as PR https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/663 updated the expected diffs. This fixes the following test cases:
    ```
    TestE2E/../../examples/generate-folders-resourcehierarchy-v3
    TestE2E/../../examples/generate-folders-resourcehierarchy-v2
    TestE2E/../../examples/generate-folders-resourcehierarchy-v1
    TestE2E/../../examples/enable-gcp-services-advanced
    TestE2E/../../examples/enable-gcp-services-simple
    TestE2E/../../tests/enable-gcp-services/nested-packages
    ```
  - kustomize should be at the latest v4. If you follow the installation instructions on kustomize.io, that installs v3. v3 will cause some kustomize specific tests to fail.
  - node and npm should be up to date. I was previously on an outdated npm version, which was causing some build/test issues. I'm currently using node v12 which is what our GH Action uses.

### Need to update test runner to copy with right permissions
For each e2e test case that we run, we copy the [directory into a temporary directory before volume mounting](https://github.com/GoogleContainerTools/kpt/blob/ac17e15376e006da7cde0761ea55159baca5ad77/pkg/test/runner/runner.go#L159).
This copy process is done using `cp -r <src> <dst>`, [via the `copyDir` function ](https://github.com/GoogleContainerTools/kpt/blob/ac17e15376e006da7cde0761ea55159baca5ad77/pkg/test/runner/util.go#L42)which modifies file permissions. We should update this function to copy with the right permissions, either with the `--preserve` flag for `cp`, eg: `cp -rp`, or using `rsync`. If not, we run into volume bind mount issues as documented in #939.
The following test cases are fixed by this:
```
TestE2E/../../examples/render-helm-chart-remote-values-file
TestE2E/../../examples/render-helm-chart-local
TestE2E/../../examples/kubeval-mount-schema
```

### Nice to have: better test logging
While looking into this, I got confused by the tests logging failures/errors despite Go marking the tests as successful. This is [also seen in our GH Action CI workflow](https://github.com/GoogleContainerTools/kpt-functions-catalog/runs/4401081701?check_suite_focus=true#step:7:211). An example snippet of such (in case the CI log is deleted from GH):
```
=== CONT  TestE2E/../../examples/starlark-validation
    runner.go:346: kpt error, stdout: ; stderr: Package "starlark-validation": 
        [RUNNING] "gcr.io/kpt-fn/starlark:unstable"
        [FAIL] "gcr.io/kpt-fn/starlark:unstable" in 3.6s
          Results:
            [ERROR] fail: it is prohibited to have private key in a configmap
          Stderr:
            "[error] : fail: it is prohibited to have private key in a configmap"
          Exit code: 1
        
        For complete results, see /tmp/kpt-pipeline-e2e-3078799965/results/results.yaml
```

This is actually a red herring when debugging since these tests are for unhappy paths (ie. they are testing for failures). We should have better logging to not throw us off when we test unhappy paths.

---

Note: I'm unable to replicate the test failures for `TestE2E/../../examples/kubeval-simple` and `TestE2E/../../examples/kubeval-imperative` that @sdowell mentions in the original report using my gLinux environment.

**Comment by natasha41575** [comment]
> kustomize should be at the latest v4. If you follow the installation instructions on kustomize.io, that installs v3. v3 will cause some kustomize specific tests to fail.

Just FYI, kustomize.io is not our website (yet), please refer to https://kubectl.docs.kubernetes.io/references/kustomize/ for all kustomize documentation.

**Comment by rquitales** [comment]
> > kustomize should be at the latest v4. If you follow the installation instructions on kustomize.io, that installs v3. v3 will cause some kustomize specific tests to fail.
> 
> Just FYI, kustomize.io is not our website (yet), please refer to https://kubectl.docs.kubernetes.io/references/kustomize/ for all kustomize documentation.

Good to know! It still looks like this source is also pointing users to install v3 by default? https://kubectl.docs.kubernetes.io/installation/kustomize/source/

**Comment by sdowell** [comment]
@rquitales Thank you for looking into this and providing such a detailed response.

>Note: I'm unable to replicate the test failures for TestE2E/../../examples/kubeval-simple and TestE2E/../../examples/kubeval-imperative that @sdowell mentions in the original report using my gLinux environment.

Did you build the `kubeval` image locally or pull it from the registry? IIRC this failure had to do with the `kubeval` image itself and only reproduced when building the image locally.

**Comment by rquitales** [comment]
Followed up on this offline. The `kubeval` tests were failing also due to file permission issues. Specifically, we copy in 
 the `openapi2jsonschema` [Python scripts with existing file permissions](https://github.com/GoogleContainerTools/kpt-functions-catalog/blob/106a8b0e4707e04eafd460985616b2af2c95ec0f/functions/ts/kubeval/build/kubeval.Dockerfile#L32). If these file permissions on the host machine are too restrictive, the `node` user within the container would not be able to execute `openapi2jsonschema` resulting in the test failures we see.

A way to overcome this is to ensure that files have less restrictive permissions when we clone the repo. We can use `umask` to set this, eg. `umask 0002` which defaults to chmod 644 for files.

Note, we probably don't need to update the `copyDir` function I initially described in my initial comment, if we initialize our dev env with the right initial file permissions.
