### ISSUE TITLE
Improve performance of openapi schema parsing in kyaml/openapi

### ISSUE THREAD

**Issue by mengqiy** [GoogleContainerTools/kpt#2651]
kpt CLI and some functions requires openapi to work. But it's very slow when parsing the openapi api in json format (https://github.com/kubernetes-sigs/kustomize/issues/3670). There are a few options (https://github.com/kubernetes-sigs/kustomize/pull/4396) we can make it faster.

**Comment by natasha41575** [comment]
Because it seems that we can get a significant performance improvement from this work, I believe that we should prioritize this, but we should be aware that of the scope. 

If we want to switch from "k8s.io/kube-openapi/pkg/validation/spec" to the "github.com/googleapis/gnostic/openapiv2", there will be a lot of changes. The underlying schema representation of the new library is different than the current library in subtle but important ways, so everywhere that the old library is currently being used will need to be rewritten. Some of these changes may be small where there are similarities in structure, while other changes will be larger. After quickly looking over where the old library is used, it seems to me that most of these tasks are doable, but that there are (1) a lot of them, (2) insufficient unit tests where they are used, and (3) most of the changes are dependent on each other and would be challenging to tackle independently. This makes it difficult to develop the changes incrementally and to understand the current state of progress at any point. 

Additionally, there are some areas where the openapi schema is used that are not covered by the tests in the kustomize repository, but will break behavior in kpt. Due to the insufficient coverage, part of this work should be to ensure that there are unit tests that provide enough coverage that we can be reasonably confident that any outside kyaml consumers, kpt included, will not see breaking changes. 

I am going to list out most of the places that I can see we are using the old library, so that we have a better understanding of what is required. This list does not cover what would be required for the next step, which is to use proto instead of JSON. 

### Namespaceability

Kyaml uses OpenAPI to determine the namespaceability of resources. Moving this over to the new library was fairly straightforward, and has been implemented in [this PR.](https://github.com/kubernetes-sigs/kustomize/pull/4432) 

### FieldMeta

Kyaml defines this type [`FieldMeta` here](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/fieldmeta/fieldmeta.go). 

This type is used to support the kpt use cases of 3-way merge in the following locations: [map.go](https://github.com/kubernetes-sigs/kustomize/blob/ff40460d3bc537a7c03b0ad9faa0987e26d40202/kyaml/yaml/walk/map.go#L113) [walk.go](https://github.com/kubernetes-sigs/kustomize/blob/ff40460d3bc537a7c03b0ad9faa0987e26d40202/kyaml/yaml/walk/walk.go#L98). For the usage in map.go, it is being directly passed into `ResourceSchema` so this work and the `ResourceSchema` work cannot be isolated. 

It is also used to support kpt setters, in the following files: [setters2/add.go](https://github.com/kubernetes-sigs/kustomize/blob/ff40460d3bc537a7c03b0ad9faa0987e26d40202/kyaml/setters2/add.go#L120) [setters2/delete.go](https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/setters2/delete.go)

### ResourceSchema

There is a type, [`ResourceSchema`](https://github.com/kubernetes-sigs/kustomize/blob/ff40460d3bc537a7c03b0ad9faa0987e26d40202/kyaml/openapi/openapi.go#L143) that is used throughout kustomize and embeds the type spec.Schema. This type is used in many, many places in kyaml, including in the merge2 and merge3 code, some filters,  setters code. A quick search via Goland shows: 
- 5 methods that return type `ResourceSchema`.
- 10 methods that initialize a struct of type `ResourceSchema`
- 6 other unclassified usages. 
- 6 methods on the type `ResourceSchema` that need to be rewritten, including one called [`Elements`](https://github.com/kubernetes-sigs/kustomize/blob/ff40460d3bc537a7c03b0ad9faa0987e26d40202/kyaml/openapi/openapi.go#L392). `Elements` is a notable method because it takes in a ResourceSchema, and returns a ResourceSchema that represents an array element. AFAICT, the new library represents lists as a different type (an array of some object) than other objects. This conversion will not be clean and may involve rewriting large parts of the code, because `Elements` is used in some of the core code. 

The latter challenge with `Elements` is probably not unique to `Elements`; my guess is we will run into similar challenges when trying to rewrite other parts of the code. I think these will be the most difficult to tackle in a clean way; it may be better to just redesign the code structure with the new library in mind. 

Changing `ResourceSchema` and rewriting all the code where it is used will be by far the biggest part of moving to the new library. 

### openapiData

There is a global variable in [openapi.go called openapiData](https://github.com/kubernetes-sigs/kustomize/blob/ff40460d3bc537a7c03b0ad9faa0987e26d40202/kyaml/openapi/openapi.go#L33) that is used to store the parsed openapi state. There are two fields that we should be considered with:

#### `schema`
This is an embedding of the type `spec.Schema` from the current openapi library and contains the entire parsed openapi schema. This is surfaced in kyaml through the function [`openapi.Schema()`](https://github.com/kubernetes-sigs/kustomize/blob/ff40460d3bc537a7c03b0ad9faa0987e26d40202/kyaml/openapi/openapi.go#L333). 

This is used in a few places, including the [starlark runtime](https://github.com/kubernetes-sigs/kustomize/blob/ff40460d3bc537a7c03b0ad9faa0987e26d40202/kyaml/fn/runtime/starlark/context.go#L44). I will have to take some time to understand what the starlark runtime is doing, right now I am not sure what starlark is doing with it. My hope is that this will be a very simple change.

There are three places it is used is to resolve references, e.g. [walk.go](https://github.com/kubernetes-sigs/kustomize/blob/ff40460d3bc537a7c03b0ad9faa0987e26d40202/kyaml/yaml/walk/walk.go#L102). I assume resolving references is possible with the new library, and if so, these changes shouldn't pose too much of a problem. 

#### `schemaByResourceType`
This maps resource typemeta to their schemas. This is surfaced by the method [SchemaForResourceType](https://github.com/kubernetes-sigs/kustomize/blob/ff40460d3bc537a7c03b0ad9faa0987e26d40202/kyaml/openapi/openapi.go#L160) which is used in a few places throughout kyaml, including setters, the function framework, and the underlying implementation of the merge code. If we are able to adapt `ResourceSchema` to use the new library, this task will happen naturally as it looks like the two are tightly intertwined. 

### ---

This list may not be exhaustive; this is just from my first look at the state of it. It is possible that there will be more we need to do even after tackling all of these tasks.

**Comment by droot** [comment]
Thanks for the detailed analysis @natasha41575 . I was under the impression that we just need to switch the serialization format in which we consume the schema,. Switching to new library has ripple effect across both the projects and changes the scope significantly.

Before brainstorming alternatives, I have a quick question:
why `k8s.io/kube-openapi/pkg/validation/spec` can not use proto format for `openapi` schema (keeping the data model same) ? [If it doesn't provide pluggable parser support, we can fork or upstream the change ]  

/cc @mengqiy

**Comment by natasha41575** [comment]
@droot Not sure if `k8s.io/kube-openapi/pkg/validation/spec` can use proto but I have not looked very deeply. Looking at this file here https://github.com/kubernetes/kube-openapi/blob/master/pkg/validation/spec/swagger.go and the library seems to revolve around JSON schemas.

**Comment by natasha41575** [comment]
This work is done.
