### ISSUE TITLE
pkg get <github-url> throws unfriendly errors when run without specifying local directory

### ISSUE THREAD

**Issue by droot** [GoogleContainerTools/kpt#301]
When I run:
```sh
kpt pkg get https://github.com/droot/httpbin@v1.0.0
Error: accepts 2 arg(s), received 1
```

We can improve the error message to say: `local_directory` or `destination` directory is missing. Or better would be to derive the destination directory from the upstream repo or pkg directory like in the above case `httpbin` could have been used by default.

**Comment by mortent** [comment]
So I'm not sure if we should do anything here. The error message is reasonably clear and the next line in the output does show the arguments needed.
In order to give more context in the error, we would need to check the format of the provided argument and then decide which of the two needed arguments are missing. Not sure if this is worth the effort.

I agree that defaulting the name of the output directory to the name of the package could be useful. It would be a bigger change since we want consistency across all the commands.

**Comment by phanimarupaka** [comment]
Agree with mortent here. The error message is clear enough currently.
