### ISSUE TITLE
improve the error message when the applying directory doesn't exist

### ISSUE THREAD

**Issue by Liujingfang1** [GoogleContainerTools/kpt#304]
`$kpt live apply hellworld` where the directory `hellworld` doesn't exist. The error message should be
The directory `hellworld` doesn't exist instead of the grouping object is not found.

**Comment by mortent** [comment]
This is already fixed in cli-utils by https://github.com/kubernetes-sigs/cli-utils/pull/70. Before this change, we ignored the error when reading the local manifests. This will be pulled into the next release of kpt.

Output from cli-utils:
![Screen Shot 2020-03-02 at 7 46 01 PM](https://user-images.githubusercontent.com/8463/75741128-83066f00-5cbe-11ea-9032-6730b8b4507a.png)
