### ISSUE TITLE
kpt live apply command gets stuck

### ISSUE THREAD

**Issue by hilliao** [GoogleContainerTools/kpt#3361]
### Expected behavior
`kpt live apply` command returns error when the infrastructure as code change can't get applied in the namespace

### Actual behavior
`kpt live apply` command  gets stuck for more than 5 minutes and had to be Ctrl+C interrupted.
### Information
steps to reproduce in [blueprints/issues/194](https://github.com/GoogleCloudPlatform/blueprints/issues/194) including all files required to reproduce the bug.

kpt version
1.0.0-beta.15

**Comment by karlkfi** [comment]
```
  --reconcile-timeout:
    The threshold for how long to wait for all resources to reconcile before
    giving up. If this flag is not set, kpt live apply will wait until
    interrupted.
```

Try `kpt live apply --reconcile-timeout 1m`

As you can see form your example:
```
iampartialpolicy.iam.cnrm.cloud.google.com/iam-storage-delete-me-356017 reconcile pending
```
There's no subsequent `reconciled` event, which means reconciliation is still pending. This is likely due to either a configuration error in the object or a controller problem not updating the status to indicate reconciliation.

**Comment by yuwenma** [comment]
closed this issue referring to @karlkfi comment
