### ISSUE TITLE
kpt cannot be used in alpine containers

### ISSUE THREAD

**Issue by wleese** [GoogleContainerTools/kpt#3511]
### Expected behavior

kpt should be usable in alpine.

### Actual behavior

kpt cannot be used in alpine containers.

### Information

The issue is due to a transitive dependency on glibc, which is pulled in by wasmtime-go.

For more details, see https://github.com/bytecodealliance/wasmtime-go/issues/21

**Comment by justinsb** [comment]
The cgo dependency is causing more challenges than anticipated, with the release process as well.

One thing we could do is to split out the wasm runner into its own executable binary - so that most people could use a precompiled version (and we'd have one that works on alpine).  OTOH it doesn't really solve the core problem, it just moves it so it only affects people that want to develop on wasm or compile-their-own-from-source.

We're also working on this for the release process, so if we can find a nice approach that makes cgo workable on all platforms that isn't too expensive, then we avoid the need for multiple binaries etc.
