### ISSUE TITLE
[Question] In the Go kpt fn SDK: What does SubObject.NestedSubObject() supposed to do?

### ISSUE THREAD

**Issue by kispaljr** [GoogleContainerTools/kpt#3931]
`NestedSubObject()` is defined here:
https://github.com/GoogleContainerTools/kpt-functions-sdk/blob/e8e9cb3c3ae2a19c22f52701d1542cf24e541df0/go/fn/object.go#L154

What does this method supposed to do?

It is not clear, because the comment above the method belongs to another method (probably `NestedStringMap`). 
Intuitively I would expect that the method returns with the `SubObject` belonging to the subtree specified by `fields...`. However, in all my tests it returns with and empty SubObject (containing only a nil pointer).
The implementation seems to suggest that it will return with a valid SubObject value, iif the subtree pointed by `fields...` contains a YAML serialized version of a SubObject value. I don't think however that this was the original intent, since a SubObject is not really JSON or YAML serializable.

**Comment by kispaljr** [comment]
If I guessed right what `NestedSubObject` supposed to do, then you can cherrypick my implementation from here: https://github.com/kispaljr/kpt-functions-sdk/tree/fix-nestedsubobject

(I cannot send a PR, since my employer doesn't allow me to sign the CLA)

**Comment by yuwenma** [comment]
@kispaljr Your understanding is exactly right. I cherry-picked your fix here https://github.com/GoogleContainerTools/kpt-functions-sdk/pull/676

A longer story is that we suggest users to use `GetMap` over `NestedSubObject` because we think `deployment.GetMap("spec").GetMap("template")` is a better practice. `NestedSubObject` supposes to be handy in two ways, 1. It gives the detailed error info (not found or parsing the object fails) so that the error handling is dedicated to users rather than in fn SDK (but this is related to a previous error handling strategy which we catch specific panics); 2. Users can concatenate the field paths in a single function to get a far descendants.  I guess some bugs are introduced when we code refactoring the Object. Thank you again for the catch and fix!
