### ISSUE TITLE
How to refer output of ComputeAddress in Kubernetes Loadbalancer type Service 

### ISSUE THREAD

**Issue by Rahul1804** [GoogleContainerTools/kpt#3994]
KPT apply-time-muatation works only if require dependencies are in the same resource group. ComputeAddress and Service resource are not in same resource group.
link - https://github.com/kubernetes-sigs/cli-utils/blob/ed4ec48b3405206c6c2200adbbc9606ea46b4257/pkg/object/graph/depends.go#LL242C7-L242C61

**Comment by karlkfi** [comment]
@Rahul1804 I think you might be confusing the ResourceGroup resource (aka package inventory) with K8s API Group.

The API group doesn't matter for depends-on/apply-time-mutation, as long as the two resource objects are in the same package/inventory/ResourceGroup.

**Comment by karlkfi** [comment]
If you actually meant to ask for cross-group dependencies as a feature request, please re-open with more details as to your use case. For now, that behavior is intentionally not allowed, because while it would work for creation ordering, it wouldn't work for deletion ordering, because there's not a good way to prevent deletion of something you don't manage.
