### ISSUE TITLE
Support serverside apply in kpt live

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#410]
We want to support serverside apply with kpt live if the cluster supports it. This will require diving deeper into how serverside apply work in order to:
- understand how we should use it from kpt
- how this will impact users how already have workloads that have been applied with clientside apply

**Comment by dflemstr** [comment]
@mortent this is becoming increasingly important as more and more operators are assuming that server-side apply is the default.  We're seeing deployments becoming slow presumably due to the increased overhead of managing client-side apply calls from the current kpt version.  Do you have an idea when this could become prioritized?

**Comment by mortent** [comment]
@dflemstr We have started looking at it in https://github.com/kubernetes-sigs/cli-utils/pull/257. I hope we can have it out in either the next release of kpt or the one after that.

**Comment by dflemstr** [comment]
That sounds great, we're following the progress with interest :) In case this doesn't land in the main release, let us know if we can be early testers of the new functionality :)

**Comment by seans3** [comment]
https://github.com/kubernetes-sigs/cli-utils/pull/257
