### ISSUE TITLE
Clear up the terminology used for prune

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#433]
We currently refer to the configmap manifest as the grouping object template, while we refer to the actual instances in the cluster as grouping objects. This gets confusing when combined with concepts for grouping resources in the live state, such as the App CRD.
I suggest we use the terms `prune inventory template` and `prune inventory`.

We should also come up with good names for the key fields in the grouping object template. We currently use the word `name`, but it is unclear if that refers to the name of the resource or the identifier used in the annotation. 
I suggest we use the terms `prune inventory identifier` and `prune inventory base name`.

**Comment by seans3** [comment]
The only issue I have with `prune` terminology is that is seems a bit restrictive, since we also use the `grouping object` for `destroy` functionality. Additionally, once there's `kpt live get` functionality, I'm guessing we would use this `grouping object` for that as well. In the end I don't feel really strongly about it, so if others are on board with the `prune` terminology--LGTM.

**Comment by mortent** [comment]
So I agree that how we use the grouping object with destroy could be a little strange, but I think it could still be considered pruning. 
If we implement kpt live get, it should _not_ depend on the current prune grouping object in any way. If we do, we have essentially created a package version of the App CRD, which is what we didn't want.

**Comment by seans3** [comment]
I propose using `inventory object` instead of `grouping object`. I have created a PR in cli-utils.

/assign
