### ISSUE TITLE
Make DIR parameter optional for frequently used cfg commands

### ISSUE THREAD

**Issue by trodge** [GoogleContainerTools/kpt#454]
Certain commands in kpt do not have dire consequences when run in the wrong directory or with wrong parameters.

A good example would be `kpt cfg set`. If the user sets something wrong or even in the wrong directory, they can easily set it back to the desired value. There is no reason to throw an error and print a page of usage when someone runs `kpt cfg set tag v1.8.0` (as shown in [these examples](https://googlecontainertools.github.io/kpt/reference/cfg/create-subst/)). Simply assume DIR is the current working directory and the workflow will be much simpler.

Some of the commands (e.g. `create-setter`) should probably stay as they are since accidentally running them in the wrong directory could be messy. However, commands like `list-setters`, `cat`, `count`, `tree`, etc. should really have an optional directory parameter. They are mostly routine tasks for which it does not make sense to burden the user with unnecessary demands.

**Comment by frankfarzan** [comment]
Agree this is causing UX friction. In almost all cases, it is more intuitive to use the current directory instead of passing a positional arg:

$ cd <dir>
$ kpt cfg set <name> <val>

Instead of:

$ kpt cfg set <dir> <name> <val>

Current, users try the intuitive command first, get an error, fiddle around with the <dir> positional argument.

As a middle ground, we can provide a global optional argument as an alternative to changing current directory:

$ kpt --dir <dir> cfg set <name> <val>

**Comment by phanimarupaka** [comment]
This has been implemented and is available in kpt v1. https://kpt.dev/installation/
