### ISSUE TITLE
What is an expected CI/CD workflow using kpt?

### ISSUE THREAD

**Issue by jlpettersson** [GoogleContainerTools/kpt#516]
Interesting tool. There is an example CI/CD workflow in the article https://opensource.googleblog.com/2020/03/kpt-packaging-up-your-kubernetes.html
but it is not so detailed. And the workflows in the docs are limited.

One idea is to have a _app-code-repo_ and a _app-config-repo_ and a CI-pipeline starts on `git push` to _app-code-repo_ and the pipeline ends with an _image_-updated to the _git-config-repo_. Then a CD-pipeline is triggered to deploy the configuration.

When reading about Google Application Delivery, it looks like they use 3 repositories, code, config and deployment: https://cloud.google.com/kubernetes-engine/docs/how-to/add-on/application-delivery#creating_new_repositories

In the docs to `kpt` it seem to be recommended to keep _code_ and _config_ in the same repository. But when I try this workflow, even commits to the _config_ subdirectory would trigger a CI-pipeline (building an image and executing tests). Also, `kpt cfg set` may update image, but it is not committed to git, so it is not possible to rollback or track image changes in the git-repository. What is the recommended CI/CD workflow and repository layout using `kpt` ?

See also #226

**Comment by mortent** [comment]
`kpt` is not really opinionated about wether the configuration and the application code is in the same git repo. For example, you can version and fetch only the configuration subdirectory with the `kpt` tools if you want to. But I can see that config changes triggering a full build of you CI pipeline might not be what you want, so in those cases it might make more sense to keep them separate.

If you want the config which contains the latest image version committed into git, you can use `kpt cfg set` or kpt functions to update your config and then commit the changes back into your config repo. If you want to do more complex transformations of your configuration with kpt functions and/or kustomize, you might want to consider using a deploy repo with the fully hydrated configuration similar to Google Application Delivery. This approach makes rollbacks pretty easy since you can just push the previous revision straight from the repo.
