### ISSUE TITLE
kpt live -n  or --namespace flags are not working for init or apply

### ISSUE THREAD

**Issue by padrian2s** [GoogleContainerTools/kpt#625]
When running `kpt live -n my_namespace init .` gives Error: unknown shorthand flag: 'n' in -n.
or `kpt live --namespace my_namespace init .` result in "Error: unknown flag: --namespace"

this cripple the ability to create different environments for the same deployments.

**Comment by mortent** [comment]
So the thinking with kpt is that you would define a setter for the namespace as part of your package. So if you wanted to deploy a package in more than one namespace, you would just set the namespace with the setter before running `kpt live init .` and `kpt live apply .`. 
If this approach doesn't work for your use case, I would be interested in hearing more about what you want to do with kpt.

**Comment by padrian2s** [comment]
I have two namespaces where I want to deploy the same k8s scripts. With "kpt live init" I can only deploy them once. Changing the namespace is going to "move" or prune the k8s artifacts from one namespace to another.

Also "kpt live init . -i dev", the "inventory-id" what suppose to do?

With kpt I want to introduce a more simple deployment scripts, not having kustomize overalys and stuff. Having two different namespaces I want do deploy the same scripts over two different namespaces, running with kpt inventory. At this point kpt looks very promising with neat features. You guys are using kpt at google in prod?

**Comment by seh** [comment]
This caught me by surprise too:
```shell
% kpt live preview .
error: objects have differing namespaces
```
My intention was to manage a set of objects that span a handful of namespaces. Being forced to split this configuration into multiple packages is a hindrance, as there are references and dependencies among these objects, and I'd prefer to manage the entire configuration as an indivisible thing. Otherwise, we could have cases where we mistakenly push a change to objects in namespace "b" that refer to objects in namespace "a," but we haven't pushed the related changes to namespace "a" yet. We then break our referential integrity that's present in the source code when projecting these subsets into the target cluster.

**Comment by mortent** [comment]
@padrian2s 
Kpt is designed to work in a gitOps environment, where the idea is that you would pull down a package (which is just a set of resources), make any changes you need to the package (using setters/substitutions or edit the yaml directly), then call `kpt live init` to generate the inventory template, then commit it to git, before you then call `kpt live apply` to update your k8s cluster. So the set of resources at this point is a git representation of the resources you want in your cluster. If you want several variations of a package, you would typically go through the previous flow separately for each of them.
We are looking into some possible changes in the way kpt handles the inventory template and the id which would make it easier to do something like what you are describing.

@seh 
We do plan to allow applying objects in different namespaces. There are some corner cases we need to cover to make sure it is safe, but we are working on it.

**Comment by seh** [comment]
Thank you, @mortent. Is this the right issue to follow that progress?

**Comment by padrian2s** [comment]
@mortent thank you!

**Comment by mortent** [comment]
So I do think we want to support a `--namespace` flag in the kpt live init command to allow users to specify where the grouping object should end up. It seems reasonable that we can automatically decide which namespace it should go into if all resources in the package have the same namespace (which I think is a pretty common situation). And then require users to explicitly set the namespace if the resources belong in different namespaces or the user just decides to keep the grouping object in another namespace. It can get difficult with clusterscoped resources and situation where namespaced resources doesn't have the namespace set, but I think we can figure that out.

**Comment by marklester** [comment]
From following this, it sounds like you are not supposed to put the namespace crd in the kpt package. It that correct?

**Comment by jijiew** [comment]
> From following this, it sounds like you are not supposed to put the namespace crd in the kpt package. It that correct?

right now, if your namespace crd is within the same namespace of other resources, it's fine. With the kpt live -namespace cmd, you will be able to specify which namespace to init with.

**Comment by mortent** [comment]
@marklester I assume you mean namespace resource rather than namespace CRD here. Kpt only cares about the built-in namespace resource type.

As @jijiew mentioned, with the proposed change, it will be possible to override the algorithm used by `kpt live init` to decide which namespace should be set on the inventory template. Right now kpt errors out if it can't decide on the namespace.

It sounds like the actual question here is about putting namespace resources in a package. This is not a problem with one important exception. It is not possible to use namespace for the inventory template that is part of the package. Basically the namespace in the inventory template must already exist before calling `kpt live apply`. The reason for this is that we create/update the inventory before we apply any of the resources to make sure we never end up with resources that have been applied but are not in the inventory. If you have use-cases where this restriction is problematic, it would be great if you could give us some more info.

**Comment by marklester** [comment]
I think being able to specify where the inventory template should be fine. Where do people usually put the inventory template? In the namespace of the app being deploy? in a namespace called inventories? default namespace?

**Comment by mortent** [comment]
@marklester So kpt doesn't really care about where you put the inventory, the important thing is that it is able to look it up during later apply operations and use it to determine if any resources should be pruned. 
If all your resources are namespaced and all belong in the same namespace (probably a common situation), I think it makes sense to put the inventory in the same namespace. 
If you have packages that either span multiple namespaces or contain cluster-scoped resources, I think it would make sense to put the inventory for these in a central place. I think in most cases these would be packages that are installed by a cluster admin, as the resource can have cluster-wide effects (like CRDs and Webhooks).

**Comment by seh** [comment]
> If you have packages that either span multiple namespaces or contain cluster-scoped resources, I think it would make sense to put the inventory for these in a central place.

I thought there was an open issue regarding _kpt_ not allowing a single inventory object to track objects in multiple namespaces. I can't find it today. Is that closed already? Can we track objects in multiple namespaces now?

**Comment by mortent** [comment]
@seh We are working on addressing this, ref some of the previous comments on this issue.
