### ISSUE TITLE
POC kustomize runs a kpt-style config function 

### ISSUE THREAD

**Issue by monopole** [GoogleContainerTools/kpt#646]
`kustomize build` runs two kinds of plugins - exec and Go.

`kpt fn run` runs config 'functions'. 

All of the above read 1) configuration data and 2) a stream of bytes representing k8s resources.  But the 'runtimes' are different, and the formats are slightly different.

This work is to modify kustomize so that it can run a config function.
pick any one of these to do a POC.
https://github.com/GoogleContainerTools/kpt-functions-catalog

The relevant kustomize code is in it's plugin loader.  this will need to share code with the kpt fn loader / aka runtime.

**Comment by aodinokov** [comment]
@Shell32-Natsu , @monopole 

Did you think about something like this when created this PoC issue?:
https://github.com/kubernetes-sigs/kustomize/pull/2597

I tried this as a transformer using config:
`
kind: Validator
metadata:
  name: valid
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: gcr.io/kustomize-functions/example-tshirt:v0.2.0
`
for the resource from copied from [1]
and got the expected result - added:
`
        resources:
          requests:
            cpu: 200m
            memory: 50M
`
Something to think about:

1. to be able to run this it was required to use  --enable_alpha_plugins and kustomize required to set $XDG_CONFIG_HOME pointing to the empty kustomize/plugin
2. I added several additional flags to the build command itself (network, enable-exec &etc, since I believe we want to use that, e.g. I would love to have some generator that could take some secrets from external db/vault via network)
3. need to make some tests - haven't looked into that yet

do you have any feedback?

[1]
https://github.com/kubernetes-sigs/kustomize/blob/master/functions/examples/injection-tshirt-sizes/local-resource/example-use.yaml#L12-L31

**Comment by Shell32-Natsu** [comment]
Hi Alexey, we have already finished the POC for running kpt function in the kustomize, although it doesn't have any code change in kustomize. Currently we are working on kustomize implementation design. We will have a design doc before implementation.

**Comment by aodinokov** [comment]
@Shell32-Natsu, np.. Thank you Donny for this info! 👍 
> We will have a design doc before implementation.

Will this doc be shared/discussed anywhere?
I'm really curious to see how this will be implemented and what features of kpt functions and its runtime will be available (e.g. mounting volumes/ work with network?).

Just a bit of background why I was so interested in that PoC :) 
I use kustomize as a 'library' (krusty) inside another application and would love to have a mechanism to extend the number of built-in plugins with external, but without additional binaries. When I looked inside krusty API - I wasn't able to find a way to extend 'builtin plugins' - only adding external binary (.so or exec-bin). And I want to distribute the app as a single binary ideally. When I saw this issue I understood it as an opportunity to finally achieve the plugin behavior without additional binaries and in additional - make it in a 'pluggable' manner. Where can I see more details? :)

cc: @monopole

**Comment by Shell32-Natsu** [comment]
We haven’t finalized that doc and I am not sure when can it be publicly reviewed. I think the first step is enabling running Kpt style function in kustomize. Then support other functionalities. But I suppose that kustomize will reuse the same code that Kpt uses so they will have same capabilities.

**Comment by aodinokov** [comment]
>I suppose that kustomize will reuse the same code that Kpt uses so they will have same capabilities.

That would be wonderful! and that would completely fit the needs I mentioned :)
I was also thinking about re-using the existing code:
The main part of the PoC I shared yesterday - file fnplugin.go was the complete copy of execplugin.go[1] with the only difference that I used the **existing** RunFns [2] instead of execution of external apps [3]. RunFns is also used in kpt [4].

To make kpt functions work with the same capabilities: network, volumes, executables and starlark I added the same flags as kpt fn commands had [5] (copied from fn run command [6]).

And the only remaining part was - to try to properly call it from loader [7] as Jeff mentioned in the issue summary:
>The relevant kustomize code is in its plugin loader.

There were couple of things I mentioned that I was concerned about.
In addition this PoC has a lot of duplicated code (especially with execplugin.go), that probably is ok for PoC, but it's better to find a way to de-duplicate that...

Anyway, thank you for sharing the status of this feature. I'm looking forward to see this feature in future versions of kustomize!

[1]
https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/plugins/execplugin/execplugin.go

[2]
https://github.com/kubernetes-sigs/kustomize/pull/2597/files#diff-1c7f40638d95255d81a98acd4cc566b4R170-R179

[3]
https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/plugins/execplugin/execplugin.go#L147-L177

[4]
https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/internal/commands/run-fns.go#L89

[5]
https://github.com/kubernetes-sigs/kustomize/pull/2597/files#diff-9249b514b53ab0e95c4224ac58541f3bR78-R93

[6]
https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/internal/commands/run-fns.go#L45-L67

[7]
https://github.com/kubernetes-sigs/kustomize/pull/2597/files#diff-8834ed8a942913ece76b31e935654cddR170-R178
