### ISSUE TITLE
`get` guide doesn't sell kpt

### ISSUE THREAD

**Issue by cflewis** [GoogleContainerTools/kpt#664]
I am learning about kpt.

I am going through the `get` guide, as this appears to be the first document I would want to follow. However, this document only has two significant operations:

1. `kpt get` a repository directory. This is just a layer on top of a `git pull` except there's some superfluous `Kptfile` generated, as the next step doesn't use it.
1. Apply YAML using `kubectl`.

Because both of these things are easily replicable with tooling the user already knows, this guide doesn't do anything to sell `kpt`. I think this guide needs to be reworked, perhaps by rolling in `kpt live` instead of `kubectl`.

**Comment by cflewis** [comment]
The flow of guides is also not good:

![image](https://user-images.githubusercontent.com/43708/82937760-8d46ab00-9f45-11ea-9e2a-878527610f2a.png)

Here "update" is before "apply". Surely "apply" is the next thing I should learn here?

**Comment by mortent** [comment]
@cflewis Thanks for your feedback. I have made some changes to the guide based on your feedback. This includes:
- Rearrange the flow of the guides for the consumer. It is not exactly what you suggested, but I think it is the order that makes the most sense.
- Add a section on how kpt allows individual versioning of kpt packages in a single repo to better communicate the benefits of using kpt instead of git directly.
