### ISSUE TITLE
CLI is very very slow

### ISSUE THREAD

**Issue by yanniszark** [GoogleContainerTools/kpt#701]
Hi all! I'm trying out kpt and I have to say I'm really excited about the solutions it presents to the hard problem of configuration management. Congrats on all the great work!
The only problem is that the CLI is giving me a hard time. I'm seeing unreasonably long run times for simple commands.
I tried installing both from source (`go get`) and from ready-built packages.

To give an example of what I'm seeing:
```console
$ time kpt pkg diff helloworld
kpt pkg diff helloworld  5.17s user 1.70s system 14% cpu 47.171 total
```

```console
$ time kpt pkg desc helloworld
   PACKAGE NAME        DIR                         REMOTE                                REMOTE PATH              REMOTE REF   REMOTE COMMIT

  hello-world-set   helloworld   https://github.com/GoogleContainerTools/kpt   /package-examples/helloworld-set   v0.5.0       3f173ad

kpt pkg desc helloworld  0.68s user 0.07s system 2% cpu 30.722 total
```

These times seem unreasonably long, especially since it doesn't really seem to do anything for most of the time (network and cpu activity seems normal).
Is this something you are seeing as well, or just something that happens on my machine?
What is it doing that makes it run so slow?

Here are some details about my OS:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by mortent** [comment]
@yanniszark Thanks for reporting this. So kpt will try to fetch the openapi schema from the kubernetes cluster defined in your current context on every invocation. There is some more information about it at https://googlecontainertools.github.io/kpt/reference/#openapi-schema.

This might be the reason you experience the kpt commands as being slow. Can you try to run the commands with the `--k8s-schema-source=builtin` flag and see if it changes anything? This flag will force kpt to use the openapi schema compiled into the binary rather than fetching it from the cluster. The disadvantage is that the schema might not match your version of Kubernetes and will not include information about any CRDs you might be using.

**Comment by mortent** [comment]
@yanniszark closing this issue. Feel free to reopen if the suggested fix didn't work.
