### ISSUE TITLE
kpt live should ignore kustomization files

### ISSUE THREAD

**Issue by mortent** [GoogleContainerTools/kpt#755]
Currently kpt live apply will fail if the folder contains a kustomization file.

**Comment by wstrange** [comment]
Shouldn't kpt live understand and apply kustomization files?

**Comment by mortent** [comment]
@wstrange that is a good question. We are working to make it easier to use kpt and kustomize together, but it is not clear whether supporting kustomize build in kpt live is the right way to go. It might be that better support for composing kpt and kustomize would be a better solution. There are some challenges around the inventory template in these situations since kustomize might change the namespace of the resources. This is something we are actively looking into.

Ignoring the kustomization files would let users apply packages that contain Kustomization files. Currently it will fail because kpt live tries to look up the kustomize GroupKind in the cluster. Longer term we might do something more, but kpt live should never try to apply the kustomization files to the cluster.

**Comment by yanniszark** [comment]
@mortent does that mean that if a user works with kustomize packages, they won't be able to use `kpt live apply`? Does it maybe make more sense to be able to specify the input YAML to `kpt live apply`? That way, a user could do `kustomize build | kpt live apply -f`

**Comment by mgoltzsche** [comment]
How about rendering the kustomization at build time only and distinguish applyable (rendered) manifests from non-applyable ones (like kustomization.yaml) using a special directory or annotation?  

It would be great if the following workflow could be supported with a kustomization as well:
* each development iteration (git commit):
```
kpt pkg sync . # fetch remote repo
kpt fn run .   # render kustomization
```
* on rollout:
```
kpt live apply . # apply rendered output that is committed with the repo
```

Unfortunately currently this doesn't work because:
* `kpt live apply .` attempts to submit the kustomization to the k8s API
* other files (e.g. patches) would appear among the applyable resources or, when not part of the kustomization function's output, would be deleted during `kpt fn run .` - not supporting idempotence.

**Comment by mgoltzsche** [comment]
I realized that my previously described workflow is already feasible when the kustomization output is written into a separate directory which is then provided to `kpt live apply` in order to apply the generated manifest only. To make that work I've prepared another kustomize kpt function: [kustomizr](https://github.com/mgoltzsche/kustomizr).

**Comment by mgoltzsche** [comment]
Now that we can use sub directories in order to deploy rendered resources how about making the workflow more project-agnostic so that one mustn't know which sub directory she needs to deploy depending on the project but call `kpt live apply .` in the main directory and let the configuration specify which sub directory should actually be deployed?  

`kpt live apply` could recursively walk through the sub directories (excluding dependencies?!) and apply only those that specify an `inventory-template.yaml` (stopping recursion at the first match). (It should still fail when it doesn't find any `inventory-template.yaml` to apply in order to help the user initially.)

**Comment by mortent** [comment]
@mgoltzsche Thanks for the feedback.

We do want to support both writing the output back into the same directory and in a new directory. I think the latter probably makes the most sense in most cases. Agree we need a way to tag resources that should be ignored by `kpt live`.

We do plan to support running apply on a root folder and have all nested folder (with a Kptfile or inventory template) be applied separately. There are some things we are still working on figuring out here, such a requirements around ordering and how to be handle pruning of entire subpackages.

**Comment by seans3** [comment]
Related PR for `no-process` annotation: https://github.com/kubernetes-sigs/kustomize/pull/2620

**Comment by mortent** [comment]
This is covered by the `config.kubernetes.io/local-config` annotation that will be available in the next kpt release.
