### ISSUE TITLE
Kpt live doesn't respect namespace context

### ISSUE THREAD

**Issue by morgante** [GoogleContainerTools/kpt#826]
When getting started with `kpt live`, it was confusing that everything goes in the `default` namespace even when I have a different namespace configured in my Kubernetes context.

`kpt live init .` should use the current context to set the namespace.

`kpt live apply .` should use the current namespace for any non-namespaced resources.

**Comment by phanimarupaka** [comment]
@mortent Can you please take a look.

**Comment by mortent** [comment]
This also applies to the `--namespace` flag. 
This is pretty straightforward to fix, but the main question is what behavior we want for the inventory here. 

I think using the namespace from the context instead of default makes sense for the `kpt live init` command. Obviously, this would only be used if the user didn't specify the namespace for the inventory directly with the `--inventory-namespace` flag.

For the apply/preview command, I think we should adopt the same behavior as kubectl, but exclude the inventory configuration (i.e. the inventory template) from this process. This means that the namespace provided either through the context or with the `--namespace` flag will never impact the namespace of the inventory object. It also means that using the `--namespace` flag will work, even if the namespace provided in the flag doesn't match the namespace of the inventory. 

For the other `kpt live` commands, providing a namespace through either the context or the flag will not have any impact.

Any thoughts? @frankfarzan @seans3 @phanimarupaka

**Comment by mortent** [comment]
This is addressed in https://github.com/kubernetes-sigs/cli-utils/pull/225 that will be part of the next kpt release.
