### ISSUE TITLE
Bug in loading directory inside docker container

### ISSUE THREAD

**Issue by prachirp** [GoogleContainerTools/kpt#856]
I'm running the following series of commands
```
kpt pkg get https://github.com/kubernetes-sigs/kustomize/examples/helloWorld helloWorld
kpt fn source helloWorld |
  kpt fn run --mount type=bind,src="$(pwd)",dst=/source,rw=true --image gcr.io/kpt-functions/kustomize-build:"${TAG}" -- path=/source/helloWorld
```
I expect this to run `kustomize build /source/helloWorld` where the build path is mounted into the docker container. But I get a permission error from [here](https://github.com/kubernetes-sigs/kustomize/blob/master/api/loader/loader.go) even though I have full permission to the helloWorld folder. 
```
fetching package examples/helloWorld from https://github.com/kubernetes-sigs/kustomize to helloWorld
[ERROR] Kustomize build command results in error: Error: Error creating new loader with git: uri looks like abs path: /source/helloWorld, dir: evalsymlink failure on '/source/helloWorld' : lstat /source/helloWorld: permission denied, get: invalid source string: /source/helloWorld
```

**Comment by prachirp** [comment]
cc @mortent 
This is a bug in `kpt fn run` because running the same command using `docker run` works. I suspect the permissions are fixed using `-u "$(id -u)"` with docker run but when I still get the error after adding `--as "$(id -u)"` to the `kpt fn run` command.
```
kpt fn source helloWorld | docker run --mount type=bind,src="$(pwd)",dst=/source -u "$(id -u)" -i gcr.io/kpt-functions/kustomize-build -d path=/source/helloWorld
apiVersion: v1
kind: ResourceList
metadata:
  name: output
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: hello
    name: the-deployment
...
```

**Comment by monopole** [comment]
I've not looked in detail here, but kustomize has a security feature that prevents it from reading from absolute paths (paths starting with `/`). This include paths specified on the command line, or in a `kustomization.yaml` file.

This can be overridden by doing
```
kustomize build --load_restrictor=none DIR
```

but ideally kustomize is run such that all paths (command line and inside files) are _relative_ (no leading `/`).


FYI, the concern was that someone would write a kustomization file that would include a ConfigMap generator that would grab data from, say,  (the absolute path) `/etc/passwd` or some such and stick it into a cluster where it could then be read to do Some Evil Thing.

It was a poor risk / cost assessment.

**Comment by monopole** [comment]
And by _relative_, i meant relative to the location of the `kustomization.yaml` file.

So `-d path=/source/helloWorld` probably violates that, but a `cd` into that dir will fix it.

**Comment by prachirp** [comment]
I don't think this is a kustomize issue because using docker run works without adding `--load-restrictor=none`.

**Comment by aodinokov** [comment]
@prachirp , what kpt version did you use?
it didn't work before https://github.com/kubernetes-sigs/kustomize/pull/2709
but it works for me with the [latest](https://github.com/GoogleContainerTools/kpt/releases/tag/v0.32.0) version, since the latest version has the updated kyaml:

```
$ ../kpt version
0.32.0
$ ../kpt pkg get https://github.com/kubernetes-sigs/kustomize/examples/helloWorld helloWorld
$ ../kpt fn source helloWorld |../kpt fn run --mount type=bind,src="$(pwd)",dst=/source,rw=true --image gcr.io/kpt-functions/kustomize-build:latest -- path=/source/helloWorld
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: the-deployment
  annotations:
    config.kubernetes.io/path: 'deployment_the-deployment.yaml'
...
```
PS
It also works without `,rw=true`. Kustomize doesn't need to write there

**Comment by prachirp** [comment]
Hey @aodinokov , I was building kpt from source before. Now I'm on the latest version and I modified the command to get around load restrictor but still seeing an error about not finding any kustomization.
```
$ kpt fn source helloWorld | kpt fn run --mount type=bind,src="$(pwd)",dst=/source,rw=true --image gcr.io/kpt-functions/kustomize-build:latest -- path=/source/helloWorld
[ERROR] Kustomize build command results in error: Error: Error creating new loader with git: uri looks like abs path: /source/helloWorld, dir: evalsymlink failure on '/source/helloWorld' : lstat /source/helloWorld: permission denied, get: invalid source string: /source/helloWorld

Error: exit status 1
```
```
$ kpt fn source helloWorld | kpt fn run --mount type=bind,src="$(pwd)/helloWorld",target=/source --image gcr.io/kpt-functions/kustomize-build:latest -- path=/source
[ERROR] Kustomize build command results in error: Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/source'

Error: exit status 1
```

**Comment by prachirp** [comment]
@aodinokov  Here are some of the examples I tried: https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/73
The examples/kustomize-build directory is a modification of the example you gave in kubernetes-sigs/kustomize#2709

**Comment by aodinokov** [comment]
@prachirp, sounds interesting :) 

Since I can't reproduce it in my env, could please you do the following in your env to try to narrow down the potential RC? : 
1. make sure you have strace installed
2. kpt just builds a cmdline and calls docker binary.  
to understand what cmdline exactly you can exec the following modified command:
```
echo "kind: x" | strace -s1024 -f ../kpt fn run --mount type=bind,src="$(pwd)",dst=/source --image gcr.io/kpt-functions/kustomize-build:latest -- path=/source/helloWorld 2>&1|grep exec
```
it should output something like
```
execve("../kpt", ["../kpt", "fn", "run", "--mount", "type=bind,src=/home/ubuntu/kpt-functions-catalog/functions/ts/t,dst=/source", "--image", "gcr.io/kpt-functions/kustomize-build:latest", "--", "path=/source/helloWorld"], 0x7ffe057e23c0 /* 22 vars */) = 0
[pid  4206] execve("/usr/bin/docker", ["docker", "run", "--rm", "-i", "-a", "STDIN", "-a", "STDOUT", "-a", "STDERR", "--network", "none", "--user", "nobody", "--security-opt=no-new-privileges", "--mount", "type=bind,source=/home/ubuntu/kpt-functions-catalog/functions/ts/t,target=/source,readonly", "-e", "LS_COLORS", "-e", "SSH_CONNECTION", "-e", "LESSCLOSE", "-e", "LANG", "-e", "XDG_SESSION_ID", "-e", "USER", "-e", "PWD", "-e", "HOME", "-e", "SSH_CLIENT", "-e", "LIBVIRT_DEFAULT_URI", "-e", "XDG_DATA_DIRS", "-e", "SSH_TTY", "-e", "MAIL", "-e", "TERM", "-e", "SHELL", "-e", "SHLVL", "-e", "LOGNAME", "-e", "XDG_RUNTIME_DIR", "-e", "PATH", "-e", "LESSOPEN", "-e", "_", "-e", "OLDPWD", "-e", "KUSTOMIZE_ENABLE_ALPHA_COMMANDS", "-e", "LOG_TO_STDERR", "-e", "STRUCTURED_RESULTS", "gcr.io/kpt-functions/kustomize-build:latest"], 0xc000137ba0 /* 25 vars */ <unfinished ...>
```
3. find in the second execve what exactly mount string is created for you case. e.g. for my example it's `--mount type=bind,source=/home/ubuntu/kpt-functions-catalog/functions/ts/t,target=/source,readonly`

NOTE: you see the other args that are passed to docker, you may build more precise command line to emulate kpt behavior just simply calling docker, similarly like you did in https://github.com/GoogleContainerTools/kpt/issues/856#issuecomment-662780108

e.g. 
```
t$ echo "kind: x" | docker run --rm -i -a STDIN -a STDOUT -a STDERR --network none --user nobody --security-opt=no-new-privileges --mount type=bind,source=/home/ubuntu/kpt-functions-catalog/functions/ts/t,target=/source,readonly gcr.io/kpt-functions/kustomize-build:latest -d path=/source/helloWorld
apiVersion: v1
kind: ResourceList
metadata:
  name: output
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
```

You should now be able to reproduce the same error with docker that you have seen with kpt.
you can also try to modify the docker run command a bit to explore what is going on in the container, e.g.
instead of the `docker run --rm -i -a STDIN -a STDOUT -a STDERR` you can just use ` docker run -it --entrypoint /bin/sh` and remove -d arg from the end.
```
t$ docker run -it --entrypoint /bin/sh --network none --user nobody --security-opt=no-new-privileges --mount type=bind,source=/home/ubuntu/kpt-functions-catalog/functions/ts/t,target=/source,readonly gcr.io/kpt-functions/kustomize-build:latest
/home/node/app $ ls /source/
helloWorld/  out/
/home/node/app $ ls /source/helloWorld/
Kptfile             README.md           configMap.yaml      deployment.yaml     kustomization.yaml  service.yaml
/home/node/app $
```
there must be kustomization.yaml

you can also try to manually run `kustomize build /source/helloWorld/` and it should work

because you will emulate the complete kpt behavior I think you'll see an error somewhere
please share what you have got

**Comment by aodinokov** [comment]
@prachirp based on your commit I created my and it passes https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/79/checks?check_run_id=910163406
I also see that your last commit wasn't tested or something went wrong:
https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/73/checks?check_run_id=909338515#step:6:135
there should be `: invalid source string: /source`
not `: invalid source string: /source/helloWorld`

try to rerun your last attempt..
I guess the previous option didn't work because you mounting home directory, but docker image is running under 'nobody' and it may not have access to that dir.
your last commit seems like should work. I'll play with it a bit more ...

**Comment by prachirp** [comment]
Hey @aodinokov You're right, something went wrong testing my last commit. I reran after making a merge commit and see the same test passed https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/73/checks?check_run_id=912311684#step:6:131
Hope to get them all working tomorrow. Thanks for so much help, especially over a weekend!
