### ISSUE TITLE
Cannot create namespace

### ISSUE THREAD

**Issue by mgoltzsche** [GoogleContainerTools/kpt#903]
Currently (kpt 0.32.0) `kpt live apply` cannot apply a namespace with its resources:
```
$ cat - > manifest.yaml <<-EOF
apiVersion: v1
kind: Namespace
metadata:
  name: example-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: example-namespace
EOF
$ kpt live init .
$ kpt live apply .
Fatal error: error when creating "generated": namespaces "example-namespace" not found
```

Apparently kpt accesses the namespace before it exists to check for its installation. The corresponding `inventory-template.yaml` was generated by `kpt live init .` with the namespace `example-namespace`.

**Comment by seans3** [comment]
This is a known problem.

The problem:

* The inventory object must be successfully applied before applying any other resource.
* If the necessary namespace for the inventory object does not exist, then the apply fails. NOTE: In order for apply/prune to work correctly and be tolerant to errors, the inventory object must successfully applied first (with the merged set of previously applied and currently applied object references).

Possible Solutions:

* Always put the inventory objects in the default namespace instead of the same namespace as the applied resources.
* Create a specific namespace for inventory objects, and store all inventory objects in this namespace (e.g. `inventory-system` namespace). The user must have permissions to create a namespace for this to work.

**Comment by seans3** [comment]
The way forward: special case the inventory namespace. Usually, the inventory object is the first object applied (this is necessary for the correctness of the pruning algorithm). If we detect that the namespace of the inventory object is also being applied, we will apply this namespace first before the inventory object. Therefore, the inventory namespace will exist when the inventory object is applied. One other consequence: we have to special case the pruning so we don't delete the inventory namespace (which would delete the inventory object; possibly inadvertently).

**Comment by mgoltzsche** [comment]
The current behavior actually makes perfectly sense. If this would work the users may not be aware of the workaround during deletion which may cause other bugs. Therefore I also imagine that the behavior remains the same as is but the error message recommends the user to use a different namespace for the inventory object.

**Comment by seans3** [comment]
Fixed by: https://github.com/kubernetes-sigs/cli-utils/pull/233

This will be incorporated into `kpt` once the next `cli-utils` build is imported.
