### ISSUE TITLE
Add --atomic flag like Helm's

### ISSUE THREAD

**Issue by wpwoodjr** [GoogleContainerTools/kpt#982]
I'd like to see a `--atomic` flag which rolls back to the previous state on failure.  Similar to helm:
```
--atomic        if set, upgrade process rolls back changes made in case of failed upgrade.
```

**Comment by mikebz** [comment]
@seans3 would the recent ResourceGroup work help with this?

**Comment by seans3** [comment]
Apologies for the delay in response.

`kpt` is one tool among many which lives in and assumes a gitops world. In this world, the **rollback** is `git revert` and `commit`, along with a `kpt live apply` of the reverted configuration files. Because of this focus, we do not believe **rollback** functionality is properly in scope for `kpt`. I will close this issue after a short amount of time.

**Comment by wpwoodjr** [comment]
Thanks for following up
